/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) holybro_euler_err_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_project CASADI_PREFIX(project)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sparsify CASADI_PREFIX(sparsify)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_sparsify(const casadi_real* x, casadi_real* y, const casadi_int* sp_y, casadi_int tr) {
  casadi_int nrow_y, ncol_y, i, el;
  const casadi_int *colind_y, *row_y;
  nrow_y = sp_y[0];
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y+ncol_y+3;
  if (tr) {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[i + row_y[el]*ncol_y]);
      }
    }
  } else {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[row_y[el]]);
      }
      x += nrow_y;
    }
  }
}

void casadi_project(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, const casadi_int* sp_y, casadi_real* w) {
  casadi_int ncol_x, ncol_y, i, el;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  for (i=0; i<ncol_x; ++i) {
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) w[row_y[el]] = 0;
    for (el=colind_x[i]; el<colind_x[i+1]; ++el) w[row_x[el]] = x[el];
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) y[el] = w[row_y[el]];
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

static const casadi_int casadi_s0[14] = 
  {3, 3, 0, 3, 6, 8, 0, 1,
  2, 0, 1, 2, 0, 1};
static const casadi_int casadi_s1[13] = 
  {3, 3, 0, 3, 5, 7, 0, 1,
  2, 0, 1, 0, 1};
static const casadi_int casadi_s2[12] = 
  {3, 3, 0, 2, 4, 6, 0, 1,
  0, 1, 0, 1};
static const casadi_int casadi_s3[11] = 
  {3, 3, 0, 2, 4, 5, 0, 1,
  0, 1, 0};
static const casadi_int casadi_s4[10] = 
  {3, 3, 0, 2, 3, 4, 0, 1,
  0, 0};
static const casadi_int casadi_s5[9] = 
  {3, 3, 0, 1, 2, 3, 0, 0,
  0};
static const casadi_int casadi_s6[8] = {3, 3, 0, 1, 2, 2, 0, 0};
static const casadi_int casadi_s7[7] = {3, 3, 0, 1, 1, 1, 0};
static const casadi_int casadi_s8[3] = {9, 1, 1};
static const casadi_int casadi_s9[3] = {4, 1, 1};
static const casadi_int casadi_s10[3] = {13, 1, 1};
static const casadi_int casadi_s11[14] = 
  {13, 1, 0, 10, 3, 4, 5, 6,
  7, 8, 9, 10, 11, 12};

static const casadi_real casadi_zeros[9] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0.};

/* holybro_euler_err_expl_vde_adj:(i0[9],i1[9],i2[4],i3[13])->(o0[13x1,10nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *w00=w+3, *w01=w+12, *w02=w+15, *w04=w+21, w05, w06, *w07=w+26, w08, *w09=w+30, *w10=w+39, *w11=w+47;
  casadi_real *w12=w+55, *w13=w+62, *w14=w+68, *w15=w+74, *w16=w+79, *w17=w+84, w18, w19, *w20=w+90, w21, w22, w23;
  casadi_real w24, w25, w26, w27, w28, w29, w30, w31, w32, w33;
  const casadi_real *cs, *ct, *wr00, *wr01, *wr02, *wr03;
  /* #0: @0 = input[1][0] */
  wr00 = arg[1] ? arg[1] : casadi_zeros;
  /* #1: {@1, @2, @3} = vertsplit(@0) */
  wr01 = wr00;
  wr02 = wr00+3;
  wr03 = wr00+6;
  /* #2: output[0][0] = @1 */
  casadi_copy(wr01, 3, res[0]);
  /* #3: @1 = zeros(3x1) */
  casadi_clear(w01, 3);
  /* #4: @4 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+6 : 0, 3, w04);
  /* #5: @5 = @4[0] */
  for (rr=(&w05), cs=w04+0; cs!=w04+1; cs+=1) *rr++ = *cs;
  /* #6: @6 = cos(@5) */
  w06 = cos( w05 );
  /* #7: @0 = zeros(3x3) */
  casadi_clear(w00, 9);
  /* #8: @7 = input[2][1] */
  casadi_copy(arg[2] ? arg[2]+1 : 0, 3, w07);
  /* #9: @7 = @7' */
  /* #10: @0 = mac(@3,@7,@0) */
  for (i=0, rr=w00; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=wr03+j, ct=w07+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #11: @8 = 0 */
  w08 = 0.;
  /* #12: @9 = @0; (@9[8] = @8) */
  casadi_copy(w00, 9, w09);
  for (rr=w09+8, cs=(&w08); rr!=w09+9; rr+=1) *rr = *cs++;
  /* #13: @10 = project(@9) */
  casadi_sparsify(w09, w10, casadi_s0, 0);
  /* #14: @11 = @10; (@11[5] = @8) */
  casadi_copy(w10, 8, w11);
  for (rr=w11+5, cs=(&w08); rr!=w11+6; rr+=1) *rr = *cs++;
  /* #15: @12 = project(@11) */
  casadi_project(w11, casadi_s0, w12, casadi_s1, w);
  /* #16: (@12[2] = @8) */
  for (rr=w12+2, cs=(&w08); rr!=w12+3; rr+=1) *rr = *cs++;
  /* #17: @13 = project(@12) */
  casadi_project(w12, casadi_s1, w13, casadi_s2, w);
  /* #18: @14 = @13; (@14[5] = @8) */
  casadi_copy(w13, 6, w14);
  for (rr=w14+5, cs=(&w08); rr!=w14+6; rr+=1) *rr = *cs++;
  /* #19: @15 = project(@14) */
  casadi_project(w14, casadi_s2, w15, casadi_s3, w);
  /* #20: @16 = @15; (@16[3] = @8) */
  casadi_copy(w15, 5, w16);
  for (rr=w16+3, cs=(&w08); rr!=w16+4; rr+=1) *rr = *cs++;
  /* #21: @17 = project(@16) */
  casadi_project(w16, casadi_s3, w17, casadi_s4, w);
  /* #22: (@17[1] = @8) */
  for (rr=w17+1, cs=(&w08); rr!=w17+2; rr+=1) *rr = *cs++;
  /* #23: @7 = project(@17) */
  casadi_project(w17, casadi_s4, w07, casadi_s5, w);
  /* #24: @18 = @7[2] */
  for (rr=(&w18), cs=w07+2; cs!=w07+3; cs+=1) *rr++ = *cs;
  /* #25: @19 = (@6*@18) */
  w19  = (w06*w18);
  /* #26: @5 = sin(@5) */
  w05 = sin( w05 );
  /* #27: (@7[2] = @8) */
  for (rr=w07+2, cs=(&w08); rr!=w07+3; rr+=1) *rr = *cs++;
  /* #28: @20 = project(@7) */
  casadi_project(w07, casadi_s5, w20, casadi_s6, w);
  /* #29: @21 = @20[1] */
  for (rr=(&w21), cs=w20+1; cs!=w20+2; cs+=1) *rr++ = *cs;
  /* #30: @22 = (@5*@21) */
  w22  = (w05*w21);
  /* #31: @19 = (@19+@22) */
  w19 += w22;
  /* #32: @22 = @4[1] */
  for (rr=(&w22), cs=w04+1; cs!=w04+2; cs+=1) *rr++ = *cs;
  /* #33: @23 = cos(@22) */
  w23 = cos( w22 );
  /* #34: @24 = sq(@23) */
  w24 = casadi_sq( w23 );
  /* #35: @19 = (@19/@24) */
  w19 /= w24;
  /* #36: @24 = sin(@22) */
  w24 = sin( w22 );
  /* #37: @25 = (@5/@23) */
  w25  = (w05/w23);
  /* #38: @26 = (@25/@23) */
  w26  = (w25/w23);
  /* #39: @27 = @10[5] */
  for (rr=(&w27), cs=w10+5; cs!=w10+6; cs+=1) *rr++ = *cs;
  /* #40: @26 = (@26*@27) */
  w26 *= w27;
  /* #41: @26 = (-@26) */
  w26 = (- w26 );
  /* #42: @28 = (@6/@23) */
  w28  = (w06/w23);
  /* #43: @29 = (@28/@23) */
  w29  = (w28/w23);
  /* #44: @30 = @0[8] */
  for (rr=(&w30), cs=w00+8; cs!=w00+9; cs+=1) *rr++ = *cs;
  /* #45: @29 = (@29*@30) */
  w29 *= w30;
  /* #46: @26 = (@26-@29) */
  w26 -= w29;
  /* #47: @26 = (@24*@26) */
  w26  = (w24*w26);
  /* #48: @19 = (@19-@26) */
  w19 -= w26;
  /* #49: @7 = @1; (@7[1] += @19) */
  casadi_copy(w01, 3, w07);
  for (rr=w07+1, cs=(&w19); rr!=w07+2; rr+=1) *rr += *cs++;
  /* #50: @27 = (@27/@23) */
  w27 /= w23;
  /* #51: @19 = @13[5] */
  for (rr=(&w19), cs=w13+5; cs!=w13+6; cs+=1) *rr++ = *cs;
  /* #52: @27 = (@27-@19) */
  w27 -= w19;
  /* #53: @22 = tan(@22) */
  w22 = tan( w22 );
  /* #54: @21 = (@22*@21) */
  w21  = (w22*w21);
  /* #55: @27 = (@27+@21) */
  w27 += w21;
  /* #56: @27 = (@6*@27) */
  w27  = (w06*w27);
  /* #57: @30 = (@30/@23) */
  w30 /= w23;
  /* #58: @21 = @15[3] */
  for (rr=(&w21), cs=w15+3; cs!=w15+4; cs+=1) *rr++ = *cs;
  /* #59: @30 = (@30+@21) */
  w30 += w21;
  /* #60: @18 = (@22*@18) */
  w18  = (w22*w18);
  /* #61: @30 = (@30+@18) */
  w30 += w18;
  /* #62: @30 = (@5*@30) */
  w30  = (w05*w30);
  /* #63: @27 = (@27-@30) */
  w27 -= w30;
  /* #64: (@7[0] += @27) */
  for (rr=w07+0, cs=(&w27); rr!=w07+1; rr+=1) *rr += *cs++;
  /* #65: @27 = @4[2] */
  for (rr=(&w27), cs=w04+2; cs!=w04+3; cs+=1) *rr++ = *cs;
  /* #66: @30 = cos(@27) */
  w30 = cos( w27 );
  /* #67: @18 = (@6*@24) */
  w18  = (w06*w24);
  /* #68: @21 = input[2][0] */
  w21 = arg[2] ? arg[2][0] : 0;
  /* #69: @19 = 0.666667 */
  w19 = 6.6666666666666663e-01;
  /* #70: @2 = (@19*@2) */
  for (i=0, rr=w02, cs=wr02; i<3; ++i) (*rr++)  = (w19*(*cs++));
  /* #71: @4 = (@21*@2) */
  for (i=0, rr=w04, cs=w02; i<3; ++i) (*rr++)  = (w21*(*cs++));
  /* #72: @4 = (-@4) */
  for (i=0, rr=w04, cs=w04; i<3; ++i) *rr++ = (- *cs++ );
  /* #73: {@21, @19, @26} = vertsplit(@4) */
  w21 = w04[0];
  w19 = w04[1];
  w26 = w04[2];
  /* #74: @29 = (@18*@19) */
  w29  = (w18*w19);
  /* #75: @31 = (@5*@21) */
  w31  = (w05*w21);
  /* #76: @29 = (@29+@31) */
  w29 += w31;
  /* #77: @29 = (@30*@29) */
  w29  = (w30*w29);
  /* #78: @27 = sin(@27) */
  w27 = sin( w27 );
  /* #79: @31 = (@18*@21) */
  w31  = (w18*w21);
  /* #80: @32 = (@5*@19) */
  w32  = (w05*w19);
  /* #81: @31 = (@31-@32) */
  w31 -= w32;
  /* #82: @31 = (@27*@31) */
  w31  = (w27*w31);
  /* #83: @29 = (@29-@31) */
  w29 -= w31;
  /* #84: (@7[2] += @29) */
  for (rr=w07+2, cs=(&w29); rr!=w07+3; rr+=1) *rr += *cs++;
  /* #85: @29 = (@27*@19) */
  w29  = (w27*w19);
  /* #86: @31 = (@6*@29) */
  w31  = (w06*w29);
  /* #87: @32 = (@30*@21) */
  w32  = (w30*w21);
  /* #88: @33 = (@6*@32) */
  w33  = (w06*w32);
  /* #89: @31 = (@31+@33) */
  w31 += w33;
  /* #90: @31 = (@23*@31) */
  w31  = (w23*w31);
  /* #91: @33 = (@6*@26) */
  w33  = (w06*w26);
  /* #92: @33 = (@24*@33) */
  w33  = (w24*w33);
  /* #93: @31 = (@31-@33) */
  w31 -= w33;
  /* #94: (@7[1] += @31) */
  for (rr=w07+1, cs=(&w31); rr!=w07+2; rr+=1) *rr += *cs++;
  /* #95: @21 = (@27*@21) */
  w21  = (w27*w21);
  /* #96: @19 = (@30*@19) */
  w19  = (w30*w19);
  /* #97: @21 = (@21-@19) */
  w21 -= w19;
  /* #98: @21 = (@6*@21) */
  w21  = (w06*w21);
  /* #99: @26 = (@23*@26) */
  w26  = (w23*w26);
  /* #100: @29 = (@24*@29) */
  w29  = (w24*w29);
  /* #101: @26 = (@26+@29) */
  w26 += w29;
  /* #102: @24 = (@24*@32) */
  w24 *= w32;
  /* #103: @26 = (@26+@24) */
  w26 += w24;
  /* #104: @26 = (@5*@26) */
  w26  = (w05*w26);
  /* #105: @21 = (@21-@26) */
  w21 -= w26;
  /* #106: (@7[0] += @21) */
  for (rr=w07+0, cs=(&w21); rr!=w07+1; rr+=1) *rr += *cs++;
  /* #107: output[0][1] = @7 */
  if (res[0]) casadi_copy(w07, 3, res[0]+3);
  /* #108: @21 = (@18*@30) */
  w21  = (w18*w30);
  /* #109: @26 = (@5*@27) */
  w26  = (w05*w27);
  /* #110: @21 = (@21+@26) */
  w21 += w26;
  /* #111: @18 = (@18*@27) */
  w18 *= w27;
  /* #112: @30 = (@5*@30) */
  w30  = (w05*w30);
  /* #113: @18 = (@18-@30) */
  w18 -= w30;
  /* #114: @23 = (@6*@23) */
  w23  = (w06*w23);
  /* #115: @7 = vertcat(@21, @18, @23) */
  rr=w07;
  *rr++ = w21;
  *rr++ = w18;
  *rr++ = w23;
  /* #116: @2 = (-@2) */
  for (i=0, rr=w02, cs=w02; i<3; ++i) *rr++ = (- *cs++ );
  /* #117: @21 = dot(@7, @2) */
  w21 = casadi_dot(3, w07, w02);
  /* #118: output[0][2] = @21 */
  if (res[0]) res[0][6] = w21;
  /* #119: @21 = zeros(3x3,1nz) */
  w21 = 0.;
  /* #120: @18 = 1 */
  w18 = 1.;
  /* #121: (@21[0] = @18) */
  for (rr=(&w21)+0, cs=(&w18); rr!=(&w21)+1; rr+=1) *rr = *cs++;
  /* #122: @20 = project(@21) */
  casadi_project((&w21), casadi_s7, w20, casadi_s6, w);
  /* #123: @21 = (@5*@22) */
  w21  = (w05*w22);
  /* #124: (@20[1] = @21) */
  for (rr=w20+1, cs=(&w21); rr!=w20+2; rr+=1) *rr = *cs++;
  /* #125: @7 = project(@20) */
  casadi_project(w20, casadi_s6, w07, casadi_s5, w);
  /* #126: @22 = (@6*@22) */
  w22  = (w06*w22);
  /* #127: (@7[2] = @22) */
  for (rr=w07+2, cs=(&w22); rr!=w07+3; rr+=1) *rr = *cs++;
  /* #128: @17 = project(@7) */
  casadi_project(w07, casadi_s5, w17, casadi_s4, w);
  /* #129: (@17[1] = @8) */
  for (rr=w17+1, cs=(&w08); rr!=w17+2; rr+=1) *rr = *cs++;
  /* #130: @15 = project(@17) */
  casadi_project(w17, casadi_s4, w15, casadi_s3, w);
  /* #131: (@15[3] = @6) */
  for (rr=w15+3, cs=(&w06); rr!=w15+4; rr+=1) *rr = *cs++;
  /* #132: @13 = project(@15) */
  casadi_project(w15, casadi_s3, w13, casadi_s2, w);
  /* #133: @5 = (-@5) */
  w05 = (- w05 );
  /* #134: (@13[5] = @5) */
  for (rr=w13+5, cs=(&w05); rr!=w13+6; rr+=1) *rr = *cs++;
  /* #135: @12 = project(@13) */
  casadi_project(w13, casadi_s2, w12, casadi_s1, w);
  /* #136: (@12[2] = @8) */
  for (rr=w12+2, cs=(&w08); rr!=w12+3; rr+=1) *rr = *cs++;
  /* #137: @10 = project(@12) */
  casadi_project(w12, casadi_s1, w10, casadi_s0, w);
  /* #138: (@10[5] = @25) */
  for (rr=w10+5, cs=(&w25); rr!=w10+6; rr+=1) *rr = *cs++;
  /* #139: @0 = dense(@10) */
  casadi_densify(w10, casadi_s0, w00, 0);
  /* #140: (@0[8] = @28) */
  for (rr=w00+8, cs=(&w28); rr!=w00+9; rr+=1) *rr = *cs++;
  /* #141: @9 = @0' */
  for (i=0, rr=w09, cs=w00; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #142: @1 = mac(@9,@3,@1) */
  for (i=0, rr=w01; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w09+j, ct=wr03+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #143: output[0][3] = @1 */
  if (res[0]) casadi_copy(w01, 3, res[0]+7);
  return 0;
}

CASADI_SYMBOL_EXPORT int holybro_euler_err_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int holybro_euler_err_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int holybro_euler_err_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void holybro_euler_err_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int holybro_euler_err_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void holybro_euler_err_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void holybro_euler_err_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void holybro_euler_err_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int holybro_euler_err_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int holybro_euler_err_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real holybro_euler_err_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* holybro_euler_err_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* holybro_euler_err_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* holybro_euler_err_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s8;
    case 1: return casadi_s8;
    case 2: return casadi_s9;
    case 3: return casadi_s10;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* holybro_euler_err_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s11;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int holybro_euler_err_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 105;
  return 0;
}

CASADI_SYMBOL_EXPORT int holybro_euler_err_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 105*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
