/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) holybro_euler_err_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_project CASADI_PREFIX(project)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_project(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, const casadi_int* sp_y, casadi_real* w) {
  casadi_int ncol_x, ncol_y, i, el;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  for (i=0; i<ncol_x; ++i) {
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) w[row_y[el]] = 0;
    for (el=colind_x[i]; el<colind_x[i+1]; ++el) w[row_x[el]] = x[el];
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) y[el] = w[row_y[el]];
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

static const casadi_int casadi_s0[7] = {3, 3, 0, 1, 1, 1, 0};
static const casadi_int casadi_s1[8] = {3, 3, 0, 1, 2, 2, 0, 0};
static const casadi_int casadi_s2[9] = 
  {3, 3, 0, 1, 2, 3, 0, 0,
  0};
static const casadi_int casadi_s3[10] = 
  {3, 3, 0, 2, 3, 4, 0, 1,
  0, 0};
static const casadi_int casadi_s4[11] = 
  {3, 3, 0, 2, 4, 5, 0, 1,
  0, 1, 0};
static const casadi_int casadi_s5[12] = 
  {3, 3, 0, 2, 4, 6, 0, 1,
  0, 1, 0, 1};
static const casadi_int casadi_s6[13] = 
  {3, 3, 0, 3, 5, 7, 0, 1,
  2, 0, 1, 0, 1};
static const casadi_int casadi_s7[14] = 
  {3, 3, 0, 3, 6, 8, 0, 1,
  2, 0, 1, 2, 0, 1};
static const casadi_int casadi_s8[3] = {9, 1, 1};
static const casadi_int casadi_s9[3] = {4, 1, 1};
static const casadi_int casadi_s10[3] = {13, 1, 1};

static const casadi_real casadi_c0[3] = {0., 0., 9.8000000000000007e+00};

/* holybro_euler_err_expl_ode_fun:(i0[9],i1[4],i2[13])->(o0[9]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *w00=w+3, w01, *w02=w+7, w03, w04, w05, w06, w07, w08, w09, w10;
  casadi_real *w11=w+18, *w12=w+20, *w13=w+24, *w14=w+29, *w15=w+35, *w16=w+42, *w17=w+50;
  const casadi_real *cs, *ct;
  /* #0: @0 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 3, w00);
  /* #1: output[0][0] = @0 */
  casadi_copy(w00, 3, res[0]);
  /* #2: @0 = [0, 0, 9.8] */
  casadi_copy(casadi_c0, 3, w00);
  /* #3: @1 = input[1][0] */
  w01 = arg[1] ? arg[1][0] : 0;
  /* #4: @2 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+6 : 0, 3, w02);
  /* #5: @3 = @2[0] */
  for (rr=(&w03), cs=w02+0; cs!=w02+1; cs+=1) *rr++ = *cs;
  /* #6: @4 = cos(@3) */
  w04 = cos( w03 );
  /* #7: @5 = @2[1] */
  for (rr=(&w05), cs=w02+1; cs!=w02+2; cs+=1) *rr++ = *cs;
  /* #8: @6 = sin(@5) */
  w06 = sin( w05 );
  /* #9: @6 = (@4*@6) */
  w06  = (w04*w06);
  /* #10: @7 = @2[2] */
  for (rr=(&w07), cs=w02+2; cs!=w02+3; cs+=1) *rr++ = *cs;
  /* #11: @8 = cos(@7) */
  w08 = cos( w07 );
  /* #12: @9 = (@6*@8) */
  w09  = (w06*w08);
  /* #13: @3 = sin(@3) */
  w03 = sin( w03 );
  /* #14: @7 = sin(@7) */
  w07 = sin( w07 );
  /* #15: @10 = (@3*@7) */
  w10  = (w03*w07);
  /* #16: @9 = (@9+@10) */
  w09 += w10;
  /* #17: @6 = (@6*@7) */
  w06 *= w07;
  /* #18: @8 = (@3*@8) */
  w08  = (w03*w08);
  /* #19: @6 = (@6-@8) */
  w06 -= w08;
  /* #20: @8 = cos(@5) */
  w08 = cos( w05 );
  /* #21: @7 = (@4*@8) */
  w07  = (w04*w08);
  /* #22: @2 = vertcat(@9, @6, @7) */
  rr=w02;
  *rr++ = w09;
  *rr++ = w06;
  *rr++ = w07;
  /* #23: @2 = (@1*@2) */
  for (i=0, rr=w02, cs=w02; i<3; ++i) (*rr++)  = (w01*(*cs++));
  /* #24: @1 = 1.5 */
  w01 = 1.5000000000000000e+00;
  /* #25: @2 = (@2/@1) */
  for (i=0, rr=w02; i<3; ++i) (*rr++) /= w01;
  /* #26: @0 = (@0-@2) */
  for (i=0, rr=w00, cs=w02; i<3; ++i) (*rr++) -= (*cs++);
  /* #27: output[0][1] = @0 */
  if (res[0]) casadi_copy(w00, 3, res[0]+3);
  /* #28: @0 = zeros(3x1) */
  casadi_clear(w00, 3);
  /* #29: @1 = zeros(3x3,1nz) */
  w01 = 0.;
  /* #30: @9 = 1 */
  w09 = 1.;
  /* #31: (@1[0] = @9) */
  for (rr=(&w01)+0, cs=(&w09); rr!=(&w01)+1; rr+=1) *rr = *cs++;
  /* #32: @11 = project(@1) */
  casadi_project((&w01), casadi_s0, w11, casadi_s1, w);
  /* #33: @5 = tan(@5) */
  w05 = tan( w05 );
  /* #34: @1 = (@3*@5) */
  w01  = (w03*w05);
  /* #35: (@11[1] = @1) */
  for (rr=w11+1, cs=(&w01); rr!=w11+2; rr+=1) *rr = *cs++;
  /* #36: @2 = project(@11) */
  casadi_project(w11, casadi_s1, w02, casadi_s2, w);
  /* #37: @5 = (@4*@5) */
  w05  = (w04*w05);
  /* #38: (@2[2] = @5) */
  for (rr=w02+2, cs=(&w05); rr!=w02+3; rr+=1) *rr = *cs++;
  /* #39: @12 = project(@2) */
  casadi_project(w02, casadi_s2, w12, casadi_s3, w);
  /* #40: @5 = 0 */
  w05 = 0.;
  /* #41: (@12[1] = @5) */
  for (rr=w12+1, cs=(&w05); rr!=w12+2; rr+=1) *rr = *cs++;
  /* #42: @13 = project(@12) */
  casadi_project(w12, casadi_s3, w13, casadi_s4, w);
  /* #43: (@13[3] = @4) */
  for (rr=w13+3, cs=(&w04); rr!=w13+4; rr+=1) *rr = *cs++;
  /* #44: @14 = project(@13) */
  casadi_project(w13, casadi_s4, w14, casadi_s5, w);
  /* #45: @1 = (-@3) */
  w01 = (- w03 );
  /* #46: (@14[5] = @1) */
  for (rr=w14+5, cs=(&w01); rr!=w14+6; rr+=1) *rr = *cs++;
  /* #47: @15 = project(@14) */
  casadi_project(w14, casadi_s5, w15, casadi_s6, w);
  /* #48: (@15[2] = @5) */
  for (rr=w15+2, cs=(&w05); rr!=w15+3; rr+=1) *rr = *cs++;
  /* #49: @16 = project(@15) */
  casadi_project(w15, casadi_s6, w16, casadi_s7, w);
  /* #50: @3 = (@3/@8) */
  w03 /= w08;
  /* #51: (@16[5] = @3) */
  for (rr=w16+5, cs=(&w03); rr!=w16+6; rr+=1) *rr = *cs++;
  /* #52: @17 = dense(@16) */
  casadi_densify(w16, casadi_s7, w17, 0);
  /* #53: @4 = (@4/@8) */
  w04 /= w08;
  /* #54: (@17[8] = @4) */
  for (rr=w17+8, cs=(&w04); rr!=w17+9; rr+=1) *rr = *cs++;
  /* #55: @2 = input[1][1] */
  casadi_copy(arg[1] ? arg[1]+1 : 0, 3, w02);
  /* #56: @0 = mac(@17,@2,@0) */
  for (i=0, rr=w00; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w17+j, ct=w02+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #57: output[0][2] = @0 */
  if (res[0]) casadi_copy(w00, 3, res[0]+6);
  return 0;
}

CASADI_SYMBOL_EXPORT int holybro_euler_err_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int holybro_euler_err_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int holybro_euler_err_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void holybro_euler_err_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int holybro_euler_err_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void holybro_euler_err_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void holybro_euler_err_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void holybro_euler_err_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int holybro_euler_err_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int holybro_euler_err_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real holybro_euler_err_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* holybro_euler_err_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* holybro_euler_err_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* holybro_euler_err_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s8;
    case 1: return casadi_s9;
    case 2: return casadi_s10;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* holybro_euler_err_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int holybro_euler_err_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 59;
  return 0;
}

CASADI_SYMBOL_EXPORT int holybro_euler_err_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 59*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
