/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) holybro_euler_err_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_project CASADI_PREFIX(project)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_project(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, const casadi_int* sp_y, casadi_real* w) {
  casadi_int ncol_x, ncol_y, i, el;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  for (i=0; i<ncol_x; ++i) {
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) w[row_y[el]] = 0;
    for (el=colind_x[i]; el<colind_x[i+1]; ++el) w[row_x[el]] = x[el];
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) y[el] = w[row_y[el]];
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[7] = {3, 3, 0, 1, 1, 1, 0};
static const casadi_int casadi_s1[8] = {3, 3, 0, 1, 2, 2, 0, 0};
static const casadi_int casadi_s2[9] = 
  {3, 3, 0, 1, 2, 3, 0, 0,
  0};
static const casadi_int casadi_s3[10] = 
  {3, 3, 0, 2, 3, 4, 0, 1,
  0, 0};
static const casadi_int casadi_s4[11] = 
  {3, 3, 0, 2, 4, 5, 0, 1,
  0, 1, 0};
static const casadi_int casadi_s5[12] = 
  {3, 3, 0, 2, 4, 6, 0, 1,
  0, 1, 0, 1};
static const casadi_int casadi_s6[13] = 
  {3, 3, 0, 3, 5, 7, 0, 1,
  2, 0, 1, 0, 1};
static const casadi_int casadi_s7[14] = 
  {3, 3, 0, 3, 6, 8, 0, 1,
  2, 0, 1, 2, 0, 1};
static const casadi_int casadi_s8[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s9[5] = {3, 1, 0, 1, 0};
static const casadi_int casadi_s10[15] = 
  {3, 3, 0, 3, 6, 9, 0, 1,
  2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s11[6] = {0, 1, 2, 3, 6, 9};
static const casadi_int casadi_s12[5] = {3, 1, 0, 1, 1};
static const casadi_int casadi_s13[5] = {3, 1, 0, 1, 2};
static const casadi_int casadi_s14[19] = 
  {9, 4, 0, 3, 6, 9, 12, 3,
  4, 5, 6, 7, 8, 6, 7, 8,
  6, 7, 8};
static const casadi_int casadi_s15[24] = 
  {4, 9, 0, 0, 0, 0, 1, 2,
  3, 6, 9, 12, 0, 0, 0, 1,
  2, 3, 1, 2, 3, 1, 2, 3};
static const casadi_int casadi_s16[3] = {9, 1, 1};
static const casadi_int casadi_s17[3] = {9, 9, 1};
static const casadi_int casadi_s18[3] = {9, 4, 1};
static const casadi_int casadi_s19[3] = {4, 1, 1};
static const casadi_int casadi_s20[3] = {13, 1, 1};

static const casadi_real casadi_c0[3] = {0., 0., 9.8000000000000007e+00};

static const casadi_real casadi_zeros[81] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0.};

/* holybro_euler_err_expl_vde_forw:(i0[9],i1[9x9],i2[9x4],i3[4],i4[13])->(o0[9],o1[9x9],o2[9x4]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *w00=w+3, w01, *w02=w+7, w03, w04, w05, w06, w07, w08, w09, w10;
  casadi_real w11, w12, w13, *w14=w+21, *w15=w+24, *w16=w+26, *w17=w+30, *w18=w+35, *w19=w+41, *w20=w+48, *w21=w+56, *w22=w+65;
  casadi_real *w24=w+149, *w25=w+158, *w26=w+167, *w27=w+176, *w28=w+185, *w29=w+194, *w30=w+203, *w31=w+212, *w32=w+221, *w33=w+230, w34, w35;
  casadi_real w36, w37, w38, w39, w40, w41, w42, *w43=w+242, w44, *w45=w+245, *w47=w+257, *w48=w+263;
  casadi_real *w49=w+275, *w50=w+311;
  const casadi_int *cii;
  const casadi_real *cs, *ct, *wr02, *wr21, *wr22, *wr23, *wr24, *wr25, *wr26, *wr27, *wr28, *wr29;
  const casadi_real *wr30, *wr31, *wr32, *wr33, *wr50;
  /* #0: @0 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 3, w00);
  /* #1: output[0][0] = @0 */
  casadi_copy(w00, 3, res[0]);
  /* #2: @0 = [0, 0, 9.8] */
  casadi_copy(casadi_c0, 3, w00);
  /* #3: @1 = input[3][0] */
  w01 = arg[3] ? arg[3][0] : 0;
  /* #4: @2 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+6 : 0, 3, w02);
  /* #5: @3 = @2[0] */
  for (rr=(&w03), cs=w02+0; cs!=w02+1; cs+=1) *rr++ = *cs;
  /* #6: @4 = cos(@3) */
  w04 = cos( w03 );
  /* #7: @5 = @2[1] */
  for (rr=(&w05), cs=w02+1; cs!=w02+2; cs+=1) *rr++ = *cs;
  /* #8: @6 = sin(@5) */
  w06 = sin( w05 );
  /* #9: @7 = (@4*@6) */
  w07  = (w04*w06);
  /* #10: @8 = @2[2] */
  for (rr=(&w08), cs=w02+2; cs!=w02+3; cs+=1) *rr++ = *cs;
  /* #11: @9 = cos(@8) */
  w09 = cos( w08 );
  /* #12: @10 = (@7*@9) */
  w10  = (w07*w09);
  /* #13: @3 = sin(@3) */
  w03 = sin( w03 );
  /* #14: @8 = sin(@8) */
  w08 = sin( w08 );
  /* #15: @11 = (@3*@8) */
  w11  = (w03*w08);
  /* #16: @10 = (@10+@11) */
  w10 += w11;
  /* #17: @11 = (@7*@8) */
  w11  = (w07*w08);
  /* #18: @12 = (@3*@9) */
  w12  = (w03*w09);
  /* #19: @11 = (@11-@12) */
  w11 -= w12;
  /* #20: @12 = cos(@5) */
  w12 = cos( w05 );
  /* #21: @13 = (@4*@12) */
  w13  = (w04*w12);
  /* #22: @2 = vertcat(@10, @11, @13) */
  rr=w02;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w13;
  /* #23: @14 = (@1*@2) */
  for (i=0, rr=w14, cs=w02; i<3; ++i) (*rr++)  = (w01*(*cs++));
  /* #24: @10 = 1.5 */
  w10 = 1.5000000000000000e+00;
  /* #25: @14 = (@14/@10) */
  for (i=0, rr=w14; i<3; ++i) (*rr++) /= w10;
  /* #26: @0 = (@0-@14) */
  for (i=0, rr=w00, cs=w14; i<3; ++i) (*rr++) -= (*cs++);
  /* #27: output[0][1] = @0 */
  if (res[0]) casadi_copy(w00, 3, res[0]+3);
  /* #28: @0 = zeros(3x1) */
  casadi_clear(w00, 3);
  /* #29: @10 = zeros(3x3,1nz) */
  w10 = 0.;
  /* #30: @11 = 1 */
  w11 = 1.;
  /* #31: (@10[0] = @11) */
  for (rr=(&w10)+0, cs=(&w11); rr!=(&w10)+1; rr+=1) *rr = *cs++;
  /* #32: @15 = project(@10) */
  casadi_project((&w10), casadi_s0, w15, casadi_s1, w);
  /* #33: @5 = tan(@5) */
  w05 = tan( w05 );
  /* #34: @10 = (@3*@5) */
  w10  = (w03*w05);
  /* #35: (@15[1] = @10) */
  for (rr=w15+1, cs=(&w10); rr!=w15+2; rr+=1) *rr = *cs++;
  /* #36: @14 = project(@15) */
  casadi_project(w15, casadi_s1, w14, casadi_s2, w);
  /* #37: @10 = (@4*@5) */
  w10  = (w04*w05);
  /* #38: (@14[2] = @10) */
  for (rr=w14+2, cs=(&w10); rr!=w14+3; rr+=1) *rr = *cs++;
  /* #39: @16 = project(@14) */
  casadi_project(w14, casadi_s2, w16, casadi_s3, w);
  /* #40: @10 = 0 */
  w10 = 0.;
  /* #41: (@16[1] = @10) */
  for (rr=w16+1, cs=(&w10); rr!=w16+2; rr+=1) *rr = *cs++;
  /* #42: @17 = project(@16) */
  casadi_project(w16, casadi_s3, w17, casadi_s4, w);
  /* #43: (@17[3] = @4) */
  for (rr=w17+3, cs=(&w04); rr!=w17+4; rr+=1) *rr = *cs++;
  /* #44: @18 = project(@17) */
  casadi_project(w17, casadi_s4, w18, casadi_s5, w);
  /* #45: @11 = (-@3) */
  w11 = (- w03 );
  /* #46: (@18[5] = @11) */
  for (rr=w18+5, cs=(&w11); rr!=w18+6; rr+=1) *rr = *cs++;
  /* #47: @19 = project(@18) */
  casadi_project(w18, casadi_s5, w19, casadi_s6, w);
  /* #48: (@19[2] = @10) */
  for (rr=w19+2, cs=(&w10); rr!=w19+3; rr+=1) *rr = *cs++;
  /* #49: @20 = project(@19) */
  casadi_project(w19, casadi_s6, w20, casadi_s7, w);
  /* #50: @10 = (@3/@12) */
  w10  = (w03/w12);
  /* #51: (@20[5] = @10) */
  for (rr=w20+5, cs=(&w10); rr!=w20+6; rr+=1) *rr = *cs++;
  /* #52: @21 = dense(@20) */
  casadi_densify(w20, casadi_s7, w21, 0);
  /* #53: @11 = (@4/@12) */
  w11  = (w04/w12);
  /* #54: (@21[8] = @11) */
  for (rr=w21+8, cs=(&w11); rr!=w21+9; rr+=1) *rr = *cs++;
  /* #55: @14 = input[3][1] */
  casadi_copy(arg[3] ? arg[3]+1 : 0, 3, w14);
  /* #56: @22 = mac(@21,@14,@0) */
  casadi_copy(w00, 3, w22);
  for (i=0, rr=w22; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w21+j, ct=w14+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #57: output[0][2] = @22 */
  if (res[0]) casadi_copy(w22, 3, res[0]+6);
  /* #58: @23 = input[1][0] */
  wr23 = arg[1] ? arg[1] : casadi_zeros;
  /* #59: {@24, @25, @26, @27, @28, @29, @30, @31, @32} = horzsplit(@23) */
  wr24 = wr23;
  wr25 = wr23+9;
  wr26 = wr23+18;
  wr27 = wr23+27;
  wr28 = wr23+36;
  wr29 = wr23+45;
  wr30 = wr23+54;
  wr31 = wr23+63;
  wr32 = wr23+72;
  /* #60: {NULL, @22, @33} = vertsplit(@24) */
  wr22 = wr24+3;
  wr33 = wr24+6;
  /* #61: output[1][0] = @22 */
  casadi_copy(wr22, 3, res[1]);
  /* #62: @13 = 0.666667 */
  w13 = 6.6666666666666663e-01;
  /* #63: @34 = @33[1] */
  w34 = wr33[1];
  /* #64: @35 = (@12*@34) */
  w35  = (w12*w34);
  /* #65: @35 = (@4*@35) */
  w35  = (w04*w35);
  /* #66: @36 = @33[0] */
  w36 = wr33[0];
  /* #67: @37 = (@3*@36) */
  w37  = (w03*w36);
  /* #68: @38 = (@6*@37) */
  w38  = (w06*w37);
  /* #69: @35 = (@35-@38) */
  w35 -= w38;
  /* #70: @38 = (@9*@35) */
  w38  = (w09*w35);
  /* #71: @39 = @33[2] */
  w39 = wr33[2];
  /* #72: @40 = (@8*@39) */
  w40  = (w08*w39);
  /* #73: @41 = (@7*@40) */
  w41  = (w07*w40);
  /* #74: @38 = (@38-@41) */
  w38 -= w41;
  /* #75: @36 = (@4*@36) */
  w36  = (w04*w36);
  /* #76: @41 = (@8*@36) */
  w41  = (w08*w36);
  /* #77: @39 = (@9*@39) */
  w39  = (w09*w39);
  /* #78: @42 = (@3*@39) */
  w42  = (w03*w39);
  /* #79: @41 = (@41+@42) */
  w41 += w42;
  /* #80: @38 = (@38+@41) */
  w38 += w41;
  /* #81: @35 = (@8*@35) */
  w35  = (w08*w35);
  /* #82: @39 = (@7*@39) */
  w39  = (w07*w39);
  /* #83: @35 = (@35+@39) */
  w35 += w39;
  /* #84: @39 = (@9*@36) */
  w39  = (w09*w36);
  /* #85: @40 = (@3*@40) */
  w40  = (w03*w40);
  /* #86: @39 = (@39-@40) */
  w39 -= w40;
  /* #87: @35 = (@35-@39) */
  w35 -= w39;
  /* #88: @39 = (@6*@34) */
  w39  = (w06*w34);
  /* #89: @40 = (@4*@39) */
  w40  = (w04*w39);
  /* #90: @40 = (-@40) */
  w40 = (- w40 );
  /* #91: @41 = (@12*@37) */
  w41  = (w12*w37);
  /* #92: @40 = (@40-@41) */
  w40 -= w41;
  /* #93: @33 = vertcat(@38, @35, @40) */
  rr=w33;
  *rr++ = w38;
  *rr++ = w35;
  *rr++ = w40;
  /* #94: @33 = (@1*@33) */
  for (i=0, rr=w33, cs=w33; i<3; ++i) (*rr++)  = (w01*(*cs++));
  /* #95: @33 = (@13*@33) */
  for (i=0, rr=w33, cs=w33; i<3; ++i) (*rr++)  = (w13*(*cs++));
  /* #96: @33 = (-@33) */
  for (i=0, rr=w33, cs=w33; i<3; ++i) *rr++ = (- *cs++ );
  /* #97: output[1][1] = @33 */
  if (res[1]) casadi_copy(w33, 3, res[1]+3);
  /* #98: @15 = zeros(3x3,2nz) */
  casadi_clear(w15, 2);
  /* #99: @38 = (@5*@36) */
  w38  = (w05*w36);
  /* #100: @35 = sq(@12) */
  w35 = casadi_sq( w12 );
  /* #101: @34 = (@34/@35) */
  w34 /= w35;
  /* #102: @40 = (@3*@34) */
  w40  = (w03*w34);
  /* #103: @38 = (@38+@40) */
  w38 += w40;
  /* #104: @43 = @15; (@43[1] += @38) */
  casadi_copy(w15, 2, w43);
  for (rr=w43+1, cs=(&w38); rr!=w43+2; rr+=1) *rr += *cs++;
  /* #105: @33 = project(@43) */
  casadi_project(w43, casadi_s1, w33, casadi_s2, w);
  /* #106: @34 = (@4*@34) */
  w34  = (w04*w34);
  /* #107: @38 = (@5*@37) */
  w38  = (w05*w37);
  /* #108: @34 = (@34-@38) */
  w34 -= w38;
  /* #109: (@33[2] += @34) */
  for (rr=w33+2, cs=(&w34); rr!=w33+3; rr+=1) *rr += *cs++;
  /* #110: @17 = project(@33) */
  casadi_project(w33, casadi_s2, w17, casadi_s4, w);
  /* #111: @34 = (-@37) */
  w34 = (- w37 );
  /* #112: (@17[3] += @34) */
  for (rr=w17+3, cs=(&w34); rr!=w17+4; rr+=1) *rr += *cs++;
  /* #113: @18 = project(@17) */
  casadi_project(w17, casadi_s4, w18, casadi_s5, w);
  /* #114: @34 = (-@36) */
  w34 = (- w36 );
  /* #115: (@18[5] += @34) */
  for (rr=w18+5, cs=(&w34); rr!=w18+6; rr+=1) *rr += *cs++;
  /* #116: @20 = project(@18) */
  casadi_project(w18, casadi_s5, w20, casadi_s7, w);
  /* #117: @36 = (@36/@12) */
  w36 /= w12;
  /* #118: @10 = (@10/@12) */
  w10 /= w12;
  /* #119: @34 = (@10*@39) */
  w34  = (w10*w39);
  /* #120: @36 = (@36+@34) */
  w36 += w34;
  /* #121: (@20[5] += @36) */
  for (rr=w20+5, cs=(&w36); rr!=w20+6; rr+=1) *rr += *cs++;
  /* #122: @24 = dense(@20) */
  casadi_densify(w20, casadi_s7, w24, 0);
  /* #123: @11 = (@11/@12) */
  w11 /= w12;
  /* #124: @39 = (@11*@39) */
  w39  = (w11*w39);
  /* #125: @37 = (@37/@12) */
  w37 /= w12;
  /* #126: @39 = (@39-@37) */
  w39 -= w37;
  /* #127: (@24[8] += @39) */
  for (rr=w24+8, cs=(&w39); rr!=w24+9; rr+=1) *rr += *cs++;
  /* #128: @33 = mac(@24,@14,@0) */
  casadi_copy(w00, 3, w33);
  for (i=0, rr=w33; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w24+j, ct=w14+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #129: output[1][2] = @33 */
  if (res[1]) casadi_copy(w33, 3, res[1]+6);
  /* #130: {NULL, @33, @22} = vertsplit(@25) */
  wr33 = wr25+3;
  wr22 = wr25+6;
  /* #131: output[1][3] = @33 */
  if (res[1]) casadi_copy(wr33, 3, res[1]+9);
  /* #132: @39 = @22[1] */
  w39 = wr22[1];
  /* #133: @37 = (@12*@39) */
  w37  = (w12*w39);
  /* #134: @37 = (@4*@37) */
  w37  = (w04*w37);
  /* #135: @36 = @22[0] */
  w36 = wr22[0];
  /* #136: @34 = (@3*@36) */
  w34  = (w03*w36);
  /* #137: @38 = (@6*@34) */
  w38  = (w06*w34);
  /* #138: @37 = (@37-@38) */
  w37 -= w38;
  /* #139: @38 = (@9*@37) */
  w38  = (w09*w37);
  /* #140: @40 = @22[2] */
  w40 = wr22[2];
  /* #141: @41 = (@8*@40) */
  w41  = (w08*w40);
  /* #142: @42 = (@7*@41) */
  w42  = (w07*w41);
  /* #143: @38 = (@38-@42) */
  w38 -= w42;
  /* #144: @36 = (@4*@36) */
  w36  = (w04*w36);
  /* #145: @42 = (@8*@36) */
  w42  = (w08*w36);
  /* #146: @40 = (@9*@40) */
  w40  = (w09*w40);
  /* #147: @44 = (@3*@40) */
  w44  = (w03*w40);
  /* #148: @42 = (@42+@44) */
  w42 += w44;
  /* #149: @38 = (@38+@42) */
  w38 += w42;
  /* #150: @37 = (@8*@37) */
  w37  = (w08*w37);
  /* #151: @40 = (@7*@40) */
  w40  = (w07*w40);
  /* #152: @37 = (@37+@40) */
  w37 += w40;
  /* #153: @40 = (@9*@36) */
  w40  = (w09*w36);
  /* #154: @41 = (@3*@41) */
  w41  = (w03*w41);
  /* #155: @40 = (@40-@41) */
  w40 -= w41;
  /* #156: @37 = (@37-@40) */
  w37 -= w40;
  /* #157: @40 = (@6*@39) */
  w40  = (w06*w39);
  /* #158: @41 = (@4*@40) */
  w41  = (w04*w40);
  /* #159: @41 = (-@41) */
  w41 = (- w41 );
  /* #160: @42 = (@12*@34) */
  w42  = (w12*w34);
  /* #161: @41 = (@41-@42) */
  w41 -= w42;
  /* #162: @22 = vertcat(@38, @37, @41) */
  rr=w22;
  *rr++ = w38;
  *rr++ = w37;
  *rr++ = w41;
  /* #163: @22 = (@1*@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) (*rr++)  = (w01*(*cs++));
  /* #164: @22 = (@13*@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) (*rr++)  = (w13*(*cs++));
  /* #165: @22 = (-@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) *rr++ = (- *cs++ );
  /* #166: output[1][4] = @22 */
  if (res[1]) casadi_copy(w22, 3, res[1]+12);
  /* #167: @38 = (@5*@36) */
  w38  = (w05*w36);
  /* #168: @39 = (@39/@35) */
  w39 /= w35;
  /* #169: @37 = (@3*@39) */
  w37  = (w03*w39);
  /* #170: @38 = (@38+@37) */
  w38 += w37;
  /* #171: @43 = @15; (@43[1] += @38) */
  casadi_copy(w15, 2, w43);
  for (rr=w43+1, cs=(&w38); rr!=w43+2; rr+=1) *rr += *cs++;
  /* #172: @22 = project(@43) */
  casadi_project(w43, casadi_s1, w22, casadi_s2, w);
  /* #173: @39 = (@4*@39) */
  w39  = (w04*w39);
  /* #174: @38 = (@5*@34) */
  w38  = (w05*w34);
  /* #175: @39 = (@39-@38) */
  w39 -= w38;
  /* #176: (@22[2] += @39) */
  for (rr=w22+2, cs=(&w39); rr!=w22+3; rr+=1) *rr += *cs++;
  /* #177: @17 = project(@22) */
  casadi_project(w22, casadi_s2, w17, casadi_s4, w);
  /* #178: @39 = (-@34) */
  w39 = (- w34 );
  /* #179: (@17[3] += @39) */
  for (rr=w17+3, cs=(&w39); rr!=w17+4; rr+=1) *rr += *cs++;
  /* #180: @18 = project(@17) */
  casadi_project(w17, casadi_s4, w18, casadi_s5, w);
  /* #181: @39 = (-@36) */
  w39 = (- w36 );
  /* #182: (@18[5] += @39) */
  for (rr=w18+5, cs=(&w39); rr!=w18+6; rr+=1) *rr += *cs++;
  /* #183: @20 = project(@18) */
  casadi_project(w18, casadi_s5, w20, casadi_s7, w);
  /* #184: @36 = (@36/@12) */
  w36 /= w12;
  /* #185: @39 = (@10*@40) */
  w39  = (w10*w40);
  /* #186: @36 = (@36+@39) */
  w36 += w39;
  /* #187: (@20[5] += @36) */
  for (rr=w20+5, cs=(&w36); rr!=w20+6; rr+=1) *rr += *cs++;
  /* #188: @25 = dense(@20) */
  casadi_densify(w20, casadi_s7, w25, 0);
  /* #189: @40 = (@11*@40) */
  w40  = (w11*w40);
  /* #190: @34 = (@34/@12) */
  w34 /= w12;
  /* #191: @40 = (@40-@34) */
  w40 -= w34;
  /* #192: (@25[8] += @40) */
  for (rr=w25+8, cs=(&w40); rr!=w25+9; rr+=1) *rr += *cs++;
  /* #193: @22 = mac(@25,@14,@0) */
  casadi_copy(w00, 3, w22);
  for (i=0, rr=w22; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w25+j, ct=w14+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #194: output[1][5] = @22 */
  if (res[1]) casadi_copy(w22, 3, res[1]+15);
  /* #195: {NULL, @22, @33} = vertsplit(@26) */
  wr22 = wr26+3;
  wr33 = wr26+6;
  /* #196: output[1][6] = @22 */
  if (res[1]) casadi_copy(wr22, 3, res[1]+18);
  /* #197: @40 = @33[1] */
  w40 = wr33[1];
  /* #198: @34 = (@12*@40) */
  w34  = (w12*w40);
  /* #199: @34 = (@4*@34) */
  w34  = (w04*w34);
  /* #200: @36 = @33[0] */
  w36 = wr33[0];
  /* #201: @39 = (@3*@36) */
  w39  = (w03*w36);
  /* #202: @38 = (@6*@39) */
  w38  = (w06*w39);
  /* #203: @34 = (@34-@38) */
  w34 -= w38;
  /* #204: @38 = (@9*@34) */
  w38  = (w09*w34);
  /* #205: @37 = @33[2] */
  w37 = wr33[2];
  /* #206: @41 = (@8*@37) */
  w41  = (w08*w37);
  /* #207: @42 = (@7*@41) */
  w42  = (w07*w41);
  /* #208: @38 = (@38-@42) */
  w38 -= w42;
  /* #209: @36 = (@4*@36) */
  w36  = (w04*w36);
  /* #210: @42 = (@8*@36) */
  w42  = (w08*w36);
  /* #211: @37 = (@9*@37) */
  w37  = (w09*w37);
  /* #212: @44 = (@3*@37) */
  w44  = (w03*w37);
  /* #213: @42 = (@42+@44) */
  w42 += w44;
  /* #214: @38 = (@38+@42) */
  w38 += w42;
  /* #215: @34 = (@8*@34) */
  w34  = (w08*w34);
  /* #216: @37 = (@7*@37) */
  w37  = (w07*w37);
  /* #217: @34 = (@34+@37) */
  w34 += w37;
  /* #218: @37 = (@9*@36) */
  w37  = (w09*w36);
  /* #219: @41 = (@3*@41) */
  w41  = (w03*w41);
  /* #220: @37 = (@37-@41) */
  w37 -= w41;
  /* #221: @34 = (@34-@37) */
  w34 -= w37;
  /* #222: @37 = (@6*@40) */
  w37  = (w06*w40);
  /* #223: @41 = (@4*@37) */
  w41  = (w04*w37);
  /* #224: @41 = (-@41) */
  w41 = (- w41 );
  /* #225: @42 = (@12*@39) */
  w42  = (w12*w39);
  /* #226: @41 = (@41-@42) */
  w41 -= w42;
  /* #227: @33 = vertcat(@38, @34, @41) */
  rr=w33;
  *rr++ = w38;
  *rr++ = w34;
  *rr++ = w41;
  /* #228: @33 = (@1*@33) */
  for (i=0, rr=w33, cs=w33; i<3; ++i) (*rr++)  = (w01*(*cs++));
  /* #229: @33 = (@13*@33) */
  for (i=0, rr=w33, cs=w33; i<3; ++i) (*rr++)  = (w13*(*cs++));
  /* #230: @33 = (-@33) */
  for (i=0, rr=w33, cs=w33; i<3; ++i) *rr++ = (- *cs++ );
  /* #231: output[1][7] = @33 */
  if (res[1]) casadi_copy(w33, 3, res[1]+21);
  /* #232: @38 = (@5*@36) */
  w38  = (w05*w36);
  /* #233: @40 = (@40/@35) */
  w40 /= w35;
  /* #234: @34 = (@3*@40) */
  w34  = (w03*w40);
  /* #235: @38 = (@38+@34) */
  w38 += w34;
  /* #236: @43 = @15; (@43[1] += @38) */
  casadi_copy(w15, 2, w43);
  for (rr=w43+1, cs=(&w38); rr!=w43+2; rr+=1) *rr += *cs++;
  /* #237: @33 = project(@43) */
  casadi_project(w43, casadi_s1, w33, casadi_s2, w);
  /* #238: @40 = (@4*@40) */
  w40  = (w04*w40);
  /* #239: @38 = (@5*@39) */
  w38  = (w05*w39);
  /* #240: @40 = (@40-@38) */
  w40 -= w38;
  /* #241: (@33[2] += @40) */
  for (rr=w33+2, cs=(&w40); rr!=w33+3; rr+=1) *rr += *cs++;
  /* #242: @17 = project(@33) */
  casadi_project(w33, casadi_s2, w17, casadi_s4, w);
  /* #243: @40 = (-@39) */
  w40 = (- w39 );
  /* #244: (@17[3] += @40) */
  for (rr=w17+3, cs=(&w40); rr!=w17+4; rr+=1) *rr += *cs++;
  /* #245: @18 = project(@17) */
  casadi_project(w17, casadi_s4, w18, casadi_s5, w);
  /* #246: @40 = (-@36) */
  w40 = (- w36 );
  /* #247: (@18[5] += @40) */
  for (rr=w18+5, cs=(&w40); rr!=w18+6; rr+=1) *rr += *cs++;
  /* #248: @20 = project(@18) */
  casadi_project(w18, casadi_s5, w20, casadi_s7, w);
  /* #249: @36 = (@36/@12) */
  w36 /= w12;
  /* #250: @40 = (@10*@37) */
  w40  = (w10*w37);
  /* #251: @36 = (@36+@40) */
  w36 += w40;
  /* #252: (@20[5] += @36) */
  for (rr=w20+5, cs=(&w36); rr!=w20+6; rr+=1) *rr += *cs++;
  /* #253: @26 = dense(@20) */
  casadi_densify(w20, casadi_s7, w26, 0);
  /* #254: @37 = (@11*@37) */
  w37  = (w11*w37);
  /* #255: @39 = (@39/@12) */
  w39 /= w12;
  /* #256: @37 = (@37-@39) */
  w37 -= w39;
  /* #257: (@26[8] += @37) */
  for (rr=w26+8, cs=(&w37); rr!=w26+9; rr+=1) *rr += *cs++;
  /* #258: @33 = mac(@26,@14,@0) */
  casadi_copy(w00, 3, w33);
  for (i=0, rr=w33; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w26+j, ct=w14+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #259: output[1][8] = @33 */
  if (res[1]) casadi_copy(w33, 3, res[1]+24);
  /* #260: {NULL, @33, @22} = vertsplit(@27) */
  wr33 = wr27+3;
  wr22 = wr27+6;
  /* #261: output[1][9] = @33 */
  if (res[1]) casadi_copy(wr33, 3, res[1]+27);
  /* #262: @37 = @22[1] */
  w37 = wr22[1];
  /* #263: @39 = (@12*@37) */
  w39  = (w12*w37);
  /* #264: @39 = (@4*@39) */
  w39  = (w04*w39);
  /* #265: @36 = @22[0] */
  w36 = wr22[0];
  /* #266: @40 = (@3*@36) */
  w40  = (w03*w36);
  /* #267: @38 = (@6*@40) */
  w38  = (w06*w40);
  /* #268: @39 = (@39-@38) */
  w39 -= w38;
  /* #269: @38 = (@9*@39) */
  w38  = (w09*w39);
  /* #270: @34 = @22[2] */
  w34 = wr22[2];
  /* #271: @41 = (@8*@34) */
  w41  = (w08*w34);
  /* #272: @42 = (@7*@41) */
  w42  = (w07*w41);
  /* #273: @38 = (@38-@42) */
  w38 -= w42;
  /* #274: @36 = (@4*@36) */
  w36  = (w04*w36);
  /* #275: @42 = (@8*@36) */
  w42  = (w08*w36);
  /* #276: @34 = (@9*@34) */
  w34  = (w09*w34);
  /* #277: @44 = (@3*@34) */
  w44  = (w03*w34);
  /* #278: @42 = (@42+@44) */
  w42 += w44;
  /* #279: @38 = (@38+@42) */
  w38 += w42;
  /* #280: @39 = (@8*@39) */
  w39  = (w08*w39);
  /* #281: @34 = (@7*@34) */
  w34  = (w07*w34);
  /* #282: @39 = (@39+@34) */
  w39 += w34;
  /* #283: @34 = (@9*@36) */
  w34  = (w09*w36);
  /* #284: @41 = (@3*@41) */
  w41  = (w03*w41);
  /* #285: @34 = (@34-@41) */
  w34 -= w41;
  /* #286: @39 = (@39-@34) */
  w39 -= w34;
  /* #287: @34 = (@6*@37) */
  w34  = (w06*w37);
  /* #288: @41 = (@4*@34) */
  w41  = (w04*w34);
  /* #289: @41 = (-@41) */
  w41 = (- w41 );
  /* #290: @42 = (@12*@40) */
  w42  = (w12*w40);
  /* #291: @41 = (@41-@42) */
  w41 -= w42;
  /* #292: @22 = vertcat(@38, @39, @41) */
  rr=w22;
  *rr++ = w38;
  *rr++ = w39;
  *rr++ = w41;
  /* #293: @22 = (@1*@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) (*rr++)  = (w01*(*cs++));
  /* #294: @22 = (@13*@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) (*rr++)  = (w13*(*cs++));
  /* #295: @22 = (-@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) *rr++ = (- *cs++ );
  /* #296: output[1][10] = @22 */
  if (res[1]) casadi_copy(w22, 3, res[1]+30);
  /* #297: @38 = (@5*@36) */
  w38  = (w05*w36);
  /* #298: @37 = (@37/@35) */
  w37 /= w35;
  /* #299: @39 = (@3*@37) */
  w39  = (w03*w37);
  /* #300: @38 = (@38+@39) */
  w38 += w39;
  /* #301: @43 = @15; (@43[1] += @38) */
  casadi_copy(w15, 2, w43);
  for (rr=w43+1, cs=(&w38); rr!=w43+2; rr+=1) *rr += *cs++;
  /* #302: @22 = project(@43) */
  casadi_project(w43, casadi_s1, w22, casadi_s2, w);
  /* #303: @37 = (@4*@37) */
  w37  = (w04*w37);
  /* #304: @38 = (@5*@40) */
  w38  = (w05*w40);
  /* #305: @37 = (@37-@38) */
  w37 -= w38;
  /* #306: (@22[2] += @37) */
  for (rr=w22+2, cs=(&w37); rr!=w22+3; rr+=1) *rr += *cs++;
  /* #307: @17 = project(@22) */
  casadi_project(w22, casadi_s2, w17, casadi_s4, w);
  /* #308: @37 = (-@40) */
  w37 = (- w40 );
  /* #309: (@17[3] += @37) */
  for (rr=w17+3, cs=(&w37); rr!=w17+4; rr+=1) *rr += *cs++;
  /* #310: @18 = project(@17) */
  casadi_project(w17, casadi_s4, w18, casadi_s5, w);
  /* #311: @37 = (-@36) */
  w37 = (- w36 );
  /* #312: (@18[5] += @37) */
  for (rr=w18+5, cs=(&w37); rr!=w18+6; rr+=1) *rr += *cs++;
  /* #313: @20 = project(@18) */
  casadi_project(w18, casadi_s5, w20, casadi_s7, w);
  /* #314: @36 = (@36/@12) */
  w36 /= w12;
  /* #315: @37 = (@10*@34) */
  w37  = (w10*w34);
  /* #316: @36 = (@36+@37) */
  w36 += w37;
  /* #317: (@20[5] += @36) */
  for (rr=w20+5, cs=(&w36); rr!=w20+6; rr+=1) *rr += *cs++;
  /* #318: @27 = dense(@20) */
  casadi_densify(w20, casadi_s7, w27, 0);
  /* #319: @34 = (@11*@34) */
  w34  = (w11*w34);
  /* #320: @40 = (@40/@12) */
  w40 /= w12;
  /* #321: @34 = (@34-@40) */
  w34 -= w40;
  /* #322: (@27[8] += @34) */
  for (rr=w27+8, cs=(&w34); rr!=w27+9; rr+=1) *rr += *cs++;
  /* #323: @22 = mac(@27,@14,@0) */
  casadi_copy(w00, 3, w22);
  for (i=0, rr=w22; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w27+j, ct=w14+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #324: output[1][11] = @22 */
  if (res[1]) casadi_copy(w22, 3, res[1]+33);
  /* #325: {NULL, @22, @33} = vertsplit(@28) */
  wr22 = wr28+3;
  wr33 = wr28+6;
  /* #326: output[1][12] = @22 */
  if (res[1]) casadi_copy(wr22, 3, res[1]+36);
  /* #327: @34 = @33[1] */
  w34 = wr33[1];
  /* #328: @40 = (@12*@34) */
  w40  = (w12*w34);
  /* #329: @40 = (@4*@40) */
  w40  = (w04*w40);
  /* #330: @36 = @33[0] */
  w36 = wr33[0];
  /* #331: @37 = (@3*@36) */
  w37  = (w03*w36);
  /* #332: @38 = (@6*@37) */
  w38  = (w06*w37);
  /* #333: @40 = (@40-@38) */
  w40 -= w38;
  /* #334: @38 = (@9*@40) */
  w38  = (w09*w40);
  /* #335: @39 = @33[2] */
  w39 = wr33[2];
  /* #336: @41 = (@8*@39) */
  w41  = (w08*w39);
  /* #337: @42 = (@7*@41) */
  w42  = (w07*w41);
  /* #338: @38 = (@38-@42) */
  w38 -= w42;
  /* #339: @36 = (@4*@36) */
  w36  = (w04*w36);
  /* #340: @42 = (@8*@36) */
  w42  = (w08*w36);
  /* #341: @39 = (@9*@39) */
  w39  = (w09*w39);
  /* #342: @44 = (@3*@39) */
  w44  = (w03*w39);
  /* #343: @42 = (@42+@44) */
  w42 += w44;
  /* #344: @38 = (@38+@42) */
  w38 += w42;
  /* #345: @40 = (@8*@40) */
  w40  = (w08*w40);
  /* #346: @39 = (@7*@39) */
  w39  = (w07*w39);
  /* #347: @40 = (@40+@39) */
  w40 += w39;
  /* #348: @39 = (@9*@36) */
  w39  = (w09*w36);
  /* #349: @41 = (@3*@41) */
  w41  = (w03*w41);
  /* #350: @39 = (@39-@41) */
  w39 -= w41;
  /* #351: @40 = (@40-@39) */
  w40 -= w39;
  /* #352: @39 = (@6*@34) */
  w39  = (w06*w34);
  /* #353: @41 = (@4*@39) */
  w41  = (w04*w39);
  /* #354: @41 = (-@41) */
  w41 = (- w41 );
  /* #355: @42 = (@12*@37) */
  w42  = (w12*w37);
  /* #356: @41 = (@41-@42) */
  w41 -= w42;
  /* #357: @33 = vertcat(@38, @40, @41) */
  rr=w33;
  *rr++ = w38;
  *rr++ = w40;
  *rr++ = w41;
  /* #358: @33 = (@1*@33) */
  for (i=0, rr=w33, cs=w33; i<3; ++i) (*rr++)  = (w01*(*cs++));
  /* #359: @33 = (@13*@33) */
  for (i=0, rr=w33, cs=w33; i<3; ++i) (*rr++)  = (w13*(*cs++));
  /* #360: @33 = (-@33) */
  for (i=0, rr=w33, cs=w33; i<3; ++i) *rr++ = (- *cs++ );
  /* #361: output[1][13] = @33 */
  if (res[1]) casadi_copy(w33, 3, res[1]+39);
  /* #362: @38 = (@5*@36) */
  w38  = (w05*w36);
  /* #363: @34 = (@34/@35) */
  w34 /= w35;
  /* #364: @40 = (@3*@34) */
  w40  = (w03*w34);
  /* #365: @38 = (@38+@40) */
  w38 += w40;
  /* #366: @43 = @15; (@43[1] += @38) */
  casadi_copy(w15, 2, w43);
  for (rr=w43+1, cs=(&w38); rr!=w43+2; rr+=1) *rr += *cs++;
  /* #367: @33 = project(@43) */
  casadi_project(w43, casadi_s1, w33, casadi_s2, w);
  /* #368: @34 = (@4*@34) */
  w34  = (w04*w34);
  /* #369: @38 = (@5*@37) */
  w38  = (w05*w37);
  /* #370: @34 = (@34-@38) */
  w34 -= w38;
  /* #371: (@33[2] += @34) */
  for (rr=w33+2, cs=(&w34); rr!=w33+3; rr+=1) *rr += *cs++;
  /* #372: @17 = project(@33) */
  casadi_project(w33, casadi_s2, w17, casadi_s4, w);
  /* #373: @34 = (-@37) */
  w34 = (- w37 );
  /* #374: (@17[3] += @34) */
  for (rr=w17+3, cs=(&w34); rr!=w17+4; rr+=1) *rr += *cs++;
  /* #375: @18 = project(@17) */
  casadi_project(w17, casadi_s4, w18, casadi_s5, w);
  /* #376: @34 = (-@36) */
  w34 = (- w36 );
  /* #377: (@18[5] += @34) */
  for (rr=w18+5, cs=(&w34); rr!=w18+6; rr+=1) *rr += *cs++;
  /* #378: @20 = project(@18) */
  casadi_project(w18, casadi_s5, w20, casadi_s7, w);
  /* #379: @36 = (@36/@12) */
  w36 /= w12;
  /* #380: @34 = (@10*@39) */
  w34  = (w10*w39);
  /* #381: @36 = (@36+@34) */
  w36 += w34;
  /* #382: (@20[5] += @36) */
  for (rr=w20+5, cs=(&w36); rr!=w20+6; rr+=1) *rr += *cs++;
  /* #383: @28 = dense(@20) */
  casadi_densify(w20, casadi_s7, w28, 0);
  /* #384: @39 = (@11*@39) */
  w39  = (w11*w39);
  /* #385: @37 = (@37/@12) */
  w37 /= w12;
  /* #386: @39 = (@39-@37) */
  w39 -= w37;
  /* #387: (@28[8] += @39) */
  for (rr=w28+8, cs=(&w39); rr!=w28+9; rr+=1) *rr += *cs++;
  /* #388: @33 = mac(@28,@14,@0) */
  casadi_copy(w00, 3, w33);
  for (i=0, rr=w33; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w28+j, ct=w14+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #389: output[1][14] = @33 */
  if (res[1]) casadi_copy(w33, 3, res[1]+42);
  /* #390: {NULL, @33, @22} = vertsplit(@29) */
  wr33 = wr29+3;
  wr22 = wr29+6;
  /* #391: output[1][15] = @33 */
  if (res[1]) casadi_copy(wr33, 3, res[1]+45);
  /* #392: @39 = @22[1] */
  w39 = wr22[1];
  /* #393: @37 = (@12*@39) */
  w37  = (w12*w39);
  /* #394: @37 = (@4*@37) */
  w37  = (w04*w37);
  /* #395: @36 = @22[0] */
  w36 = wr22[0];
  /* #396: @34 = (@3*@36) */
  w34  = (w03*w36);
  /* #397: @38 = (@6*@34) */
  w38  = (w06*w34);
  /* #398: @37 = (@37-@38) */
  w37 -= w38;
  /* #399: @38 = (@9*@37) */
  w38  = (w09*w37);
  /* #400: @40 = @22[2] */
  w40 = wr22[2];
  /* #401: @41 = (@8*@40) */
  w41  = (w08*w40);
  /* #402: @42 = (@7*@41) */
  w42  = (w07*w41);
  /* #403: @38 = (@38-@42) */
  w38 -= w42;
  /* #404: @36 = (@4*@36) */
  w36  = (w04*w36);
  /* #405: @42 = (@8*@36) */
  w42  = (w08*w36);
  /* #406: @40 = (@9*@40) */
  w40  = (w09*w40);
  /* #407: @44 = (@3*@40) */
  w44  = (w03*w40);
  /* #408: @42 = (@42+@44) */
  w42 += w44;
  /* #409: @38 = (@38+@42) */
  w38 += w42;
  /* #410: @37 = (@8*@37) */
  w37  = (w08*w37);
  /* #411: @40 = (@7*@40) */
  w40  = (w07*w40);
  /* #412: @37 = (@37+@40) */
  w37 += w40;
  /* #413: @40 = (@9*@36) */
  w40  = (w09*w36);
  /* #414: @41 = (@3*@41) */
  w41  = (w03*w41);
  /* #415: @40 = (@40-@41) */
  w40 -= w41;
  /* #416: @37 = (@37-@40) */
  w37 -= w40;
  /* #417: @40 = (@6*@39) */
  w40  = (w06*w39);
  /* #418: @41 = (@4*@40) */
  w41  = (w04*w40);
  /* #419: @41 = (-@41) */
  w41 = (- w41 );
  /* #420: @42 = (@12*@34) */
  w42  = (w12*w34);
  /* #421: @41 = (@41-@42) */
  w41 -= w42;
  /* #422: @22 = vertcat(@38, @37, @41) */
  rr=w22;
  *rr++ = w38;
  *rr++ = w37;
  *rr++ = w41;
  /* #423: @22 = (@1*@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) (*rr++)  = (w01*(*cs++));
  /* #424: @22 = (@13*@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) (*rr++)  = (w13*(*cs++));
  /* #425: @22 = (-@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) *rr++ = (- *cs++ );
  /* #426: output[1][16] = @22 */
  if (res[1]) casadi_copy(w22, 3, res[1]+48);
  /* #427: @38 = (@5*@36) */
  w38  = (w05*w36);
  /* #428: @39 = (@39/@35) */
  w39 /= w35;
  /* #429: @37 = (@3*@39) */
  w37  = (w03*w39);
  /* #430: @38 = (@38+@37) */
  w38 += w37;
  /* #431: @43 = @15; (@43[1] += @38) */
  casadi_copy(w15, 2, w43);
  for (rr=w43+1, cs=(&w38); rr!=w43+2; rr+=1) *rr += *cs++;
  /* #432: @22 = project(@43) */
  casadi_project(w43, casadi_s1, w22, casadi_s2, w);
  /* #433: @39 = (@4*@39) */
  w39  = (w04*w39);
  /* #434: @38 = (@5*@34) */
  w38  = (w05*w34);
  /* #435: @39 = (@39-@38) */
  w39 -= w38;
  /* #436: (@22[2] += @39) */
  for (rr=w22+2, cs=(&w39); rr!=w22+3; rr+=1) *rr += *cs++;
  /* #437: @17 = project(@22) */
  casadi_project(w22, casadi_s2, w17, casadi_s4, w);
  /* #438: @39 = (-@34) */
  w39 = (- w34 );
  /* #439: (@17[3] += @39) */
  for (rr=w17+3, cs=(&w39); rr!=w17+4; rr+=1) *rr += *cs++;
  /* #440: @18 = project(@17) */
  casadi_project(w17, casadi_s4, w18, casadi_s5, w);
  /* #441: @39 = (-@36) */
  w39 = (- w36 );
  /* #442: (@18[5] += @39) */
  for (rr=w18+5, cs=(&w39); rr!=w18+6; rr+=1) *rr += *cs++;
  /* #443: @20 = project(@18) */
  casadi_project(w18, casadi_s5, w20, casadi_s7, w);
  /* #444: @36 = (@36/@12) */
  w36 /= w12;
  /* #445: @39 = (@10*@40) */
  w39  = (w10*w40);
  /* #446: @36 = (@36+@39) */
  w36 += w39;
  /* #447: (@20[5] += @36) */
  for (rr=w20+5, cs=(&w36); rr!=w20+6; rr+=1) *rr += *cs++;
  /* #448: @29 = dense(@20) */
  casadi_densify(w20, casadi_s7, w29, 0);
  /* #449: @40 = (@11*@40) */
  w40  = (w11*w40);
  /* #450: @34 = (@34/@12) */
  w34 /= w12;
  /* #451: @40 = (@40-@34) */
  w40 -= w34;
  /* #452: (@29[8] += @40) */
  for (rr=w29+8, cs=(&w40); rr!=w29+9; rr+=1) *rr += *cs++;
  /* #453: @22 = mac(@29,@14,@0) */
  casadi_copy(w00, 3, w22);
  for (i=0, rr=w22; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w29+j, ct=w14+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #454: output[1][17] = @22 */
  if (res[1]) casadi_copy(w22, 3, res[1]+51);
  /* #455: {NULL, @22, @33} = vertsplit(@30) */
  wr22 = wr30+3;
  wr33 = wr30+6;
  /* #456: output[1][18] = @22 */
  if (res[1]) casadi_copy(wr22, 3, res[1]+54);
  /* #457: @40 = @33[1] */
  w40 = wr33[1];
  /* #458: @34 = (@12*@40) */
  w34  = (w12*w40);
  /* #459: @34 = (@4*@34) */
  w34  = (w04*w34);
  /* #460: @36 = @33[0] */
  w36 = wr33[0];
  /* #461: @39 = (@3*@36) */
  w39  = (w03*w36);
  /* #462: @38 = (@6*@39) */
  w38  = (w06*w39);
  /* #463: @34 = (@34-@38) */
  w34 -= w38;
  /* #464: @38 = (@9*@34) */
  w38  = (w09*w34);
  /* #465: @37 = @33[2] */
  w37 = wr33[2];
  /* #466: @41 = (@8*@37) */
  w41  = (w08*w37);
  /* #467: @42 = (@7*@41) */
  w42  = (w07*w41);
  /* #468: @38 = (@38-@42) */
  w38 -= w42;
  /* #469: @36 = (@4*@36) */
  w36  = (w04*w36);
  /* #470: @42 = (@8*@36) */
  w42  = (w08*w36);
  /* #471: @37 = (@9*@37) */
  w37  = (w09*w37);
  /* #472: @44 = (@3*@37) */
  w44  = (w03*w37);
  /* #473: @42 = (@42+@44) */
  w42 += w44;
  /* #474: @38 = (@38+@42) */
  w38 += w42;
  /* #475: @34 = (@8*@34) */
  w34  = (w08*w34);
  /* #476: @37 = (@7*@37) */
  w37  = (w07*w37);
  /* #477: @34 = (@34+@37) */
  w34 += w37;
  /* #478: @37 = (@9*@36) */
  w37  = (w09*w36);
  /* #479: @41 = (@3*@41) */
  w41  = (w03*w41);
  /* #480: @37 = (@37-@41) */
  w37 -= w41;
  /* #481: @34 = (@34-@37) */
  w34 -= w37;
  /* #482: @37 = (@6*@40) */
  w37  = (w06*w40);
  /* #483: @41 = (@4*@37) */
  w41  = (w04*w37);
  /* #484: @41 = (-@41) */
  w41 = (- w41 );
  /* #485: @42 = (@12*@39) */
  w42  = (w12*w39);
  /* #486: @41 = (@41-@42) */
  w41 -= w42;
  /* #487: @33 = vertcat(@38, @34, @41) */
  rr=w33;
  *rr++ = w38;
  *rr++ = w34;
  *rr++ = w41;
  /* #488: @33 = (@1*@33) */
  for (i=0, rr=w33, cs=w33; i<3; ++i) (*rr++)  = (w01*(*cs++));
  /* #489: @33 = (@13*@33) */
  for (i=0, rr=w33, cs=w33; i<3; ++i) (*rr++)  = (w13*(*cs++));
  /* #490: @33 = (-@33) */
  for (i=0, rr=w33, cs=w33; i<3; ++i) *rr++ = (- *cs++ );
  /* #491: output[1][19] = @33 */
  if (res[1]) casadi_copy(w33, 3, res[1]+57);
  /* #492: @38 = (@5*@36) */
  w38  = (w05*w36);
  /* #493: @40 = (@40/@35) */
  w40 /= w35;
  /* #494: @34 = (@3*@40) */
  w34  = (w03*w40);
  /* #495: @38 = (@38+@34) */
  w38 += w34;
  /* #496: @43 = @15; (@43[1] += @38) */
  casadi_copy(w15, 2, w43);
  for (rr=w43+1, cs=(&w38); rr!=w43+2; rr+=1) *rr += *cs++;
  /* #497: @33 = project(@43) */
  casadi_project(w43, casadi_s1, w33, casadi_s2, w);
  /* #498: @40 = (@4*@40) */
  w40  = (w04*w40);
  /* #499: @38 = (@5*@39) */
  w38  = (w05*w39);
  /* #500: @40 = (@40-@38) */
  w40 -= w38;
  /* #501: (@33[2] += @40) */
  for (rr=w33+2, cs=(&w40); rr!=w33+3; rr+=1) *rr += *cs++;
  /* #502: @17 = project(@33) */
  casadi_project(w33, casadi_s2, w17, casadi_s4, w);
  /* #503: @40 = (-@39) */
  w40 = (- w39 );
  /* #504: (@17[3] += @40) */
  for (rr=w17+3, cs=(&w40); rr!=w17+4; rr+=1) *rr += *cs++;
  /* #505: @18 = project(@17) */
  casadi_project(w17, casadi_s4, w18, casadi_s5, w);
  /* #506: @40 = (-@36) */
  w40 = (- w36 );
  /* #507: (@18[5] += @40) */
  for (rr=w18+5, cs=(&w40); rr!=w18+6; rr+=1) *rr += *cs++;
  /* #508: @20 = project(@18) */
  casadi_project(w18, casadi_s5, w20, casadi_s7, w);
  /* #509: @36 = (@36/@12) */
  w36 /= w12;
  /* #510: @40 = (@10*@37) */
  w40  = (w10*w37);
  /* #511: @36 = (@36+@40) */
  w36 += w40;
  /* #512: (@20[5] += @36) */
  for (rr=w20+5, cs=(&w36); rr!=w20+6; rr+=1) *rr += *cs++;
  /* #513: @30 = dense(@20) */
  casadi_densify(w20, casadi_s7, w30, 0);
  /* #514: @37 = (@11*@37) */
  w37  = (w11*w37);
  /* #515: @39 = (@39/@12) */
  w39 /= w12;
  /* #516: @37 = (@37-@39) */
  w37 -= w39;
  /* #517: (@30[8] += @37) */
  for (rr=w30+8, cs=(&w37); rr!=w30+9; rr+=1) *rr += *cs++;
  /* #518: @33 = mac(@30,@14,@0) */
  casadi_copy(w00, 3, w33);
  for (i=0, rr=w33; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w30+j, ct=w14+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #519: output[1][20] = @33 */
  if (res[1]) casadi_copy(w33, 3, res[1]+60);
  /* #520: {NULL, @33, @22} = vertsplit(@31) */
  wr33 = wr31+3;
  wr22 = wr31+6;
  /* #521: output[1][21] = @33 */
  if (res[1]) casadi_copy(wr33, 3, res[1]+63);
  /* #522: @37 = @22[1] */
  w37 = wr22[1];
  /* #523: @39 = (@12*@37) */
  w39  = (w12*w37);
  /* #524: @39 = (@4*@39) */
  w39  = (w04*w39);
  /* #525: @36 = @22[0] */
  w36 = wr22[0];
  /* #526: @40 = (@3*@36) */
  w40  = (w03*w36);
  /* #527: @38 = (@6*@40) */
  w38  = (w06*w40);
  /* #528: @39 = (@39-@38) */
  w39 -= w38;
  /* #529: @38 = (@9*@39) */
  w38  = (w09*w39);
  /* #530: @34 = @22[2] */
  w34 = wr22[2];
  /* #531: @41 = (@8*@34) */
  w41  = (w08*w34);
  /* #532: @42 = (@7*@41) */
  w42  = (w07*w41);
  /* #533: @38 = (@38-@42) */
  w38 -= w42;
  /* #534: @36 = (@4*@36) */
  w36  = (w04*w36);
  /* #535: @42 = (@8*@36) */
  w42  = (w08*w36);
  /* #536: @34 = (@9*@34) */
  w34  = (w09*w34);
  /* #537: @44 = (@3*@34) */
  w44  = (w03*w34);
  /* #538: @42 = (@42+@44) */
  w42 += w44;
  /* #539: @38 = (@38+@42) */
  w38 += w42;
  /* #540: @39 = (@8*@39) */
  w39  = (w08*w39);
  /* #541: @34 = (@7*@34) */
  w34  = (w07*w34);
  /* #542: @39 = (@39+@34) */
  w39 += w34;
  /* #543: @34 = (@9*@36) */
  w34  = (w09*w36);
  /* #544: @41 = (@3*@41) */
  w41  = (w03*w41);
  /* #545: @34 = (@34-@41) */
  w34 -= w41;
  /* #546: @39 = (@39-@34) */
  w39 -= w34;
  /* #547: @34 = (@6*@37) */
  w34  = (w06*w37);
  /* #548: @41 = (@4*@34) */
  w41  = (w04*w34);
  /* #549: @41 = (-@41) */
  w41 = (- w41 );
  /* #550: @42 = (@12*@40) */
  w42  = (w12*w40);
  /* #551: @41 = (@41-@42) */
  w41 -= w42;
  /* #552: @22 = vertcat(@38, @39, @41) */
  rr=w22;
  *rr++ = w38;
  *rr++ = w39;
  *rr++ = w41;
  /* #553: @22 = (@1*@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) (*rr++)  = (w01*(*cs++));
  /* #554: @22 = (@13*@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) (*rr++)  = (w13*(*cs++));
  /* #555: @22 = (-@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) *rr++ = (- *cs++ );
  /* #556: output[1][22] = @22 */
  if (res[1]) casadi_copy(w22, 3, res[1]+66);
  /* #557: @38 = (@5*@36) */
  w38  = (w05*w36);
  /* #558: @37 = (@37/@35) */
  w37 /= w35;
  /* #559: @39 = (@3*@37) */
  w39  = (w03*w37);
  /* #560: @38 = (@38+@39) */
  w38 += w39;
  /* #561: @43 = @15; (@43[1] += @38) */
  casadi_copy(w15, 2, w43);
  for (rr=w43+1, cs=(&w38); rr!=w43+2; rr+=1) *rr += *cs++;
  /* #562: @22 = project(@43) */
  casadi_project(w43, casadi_s1, w22, casadi_s2, w);
  /* #563: @37 = (@4*@37) */
  w37  = (w04*w37);
  /* #564: @38 = (@5*@40) */
  w38  = (w05*w40);
  /* #565: @37 = (@37-@38) */
  w37 -= w38;
  /* #566: (@22[2] += @37) */
  for (rr=w22+2, cs=(&w37); rr!=w22+3; rr+=1) *rr += *cs++;
  /* #567: @17 = project(@22) */
  casadi_project(w22, casadi_s2, w17, casadi_s4, w);
  /* #568: @37 = (-@40) */
  w37 = (- w40 );
  /* #569: (@17[3] += @37) */
  for (rr=w17+3, cs=(&w37); rr!=w17+4; rr+=1) *rr += *cs++;
  /* #570: @18 = project(@17) */
  casadi_project(w17, casadi_s4, w18, casadi_s5, w);
  /* #571: @37 = (-@36) */
  w37 = (- w36 );
  /* #572: (@18[5] += @37) */
  for (rr=w18+5, cs=(&w37); rr!=w18+6; rr+=1) *rr += *cs++;
  /* #573: @20 = project(@18) */
  casadi_project(w18, casadi_s5, w20, casadi_s7, w);
  /* #574: @36 = (@36/@12) */
  w36 /= w12;
  /* #575: @37 = (@10*@34) */
  w37  = (w10*w34);
  /* #576: @36 = (@36+@37) */
  w36 += w37;
  /* #577: (@20[5] += @36) */
  for (rr=w20+5, cs=(&w36); rr!=w20+6; rr+=1) *rr += *cs++;
  /* #578: @31 = dense(@20) */
  casadi_densify(w20, casadi_s7, w31, 0);
  /* #579: @34 = (@11*@34) */
  w34  = (w11*w34);
  /* #580: @40 = (@40/@12) */
  w40 /= w12;
  /* #581: @34 = (@34-@40) */
  w34 -= w40;
  /* #582: (@31[8] += @34) */
  for (rr=w31+8, cs=(&w34); rr!=w31+9; rr+=1) *rr += *cs++;
  /* #583: @22 = mac(@31,@14,@0) */
  casadi_copy(w00, 3, w22);
  for (i=0, rr=w22; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w31+j, ct=w14+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #584: output[1][23] = @22 */
  if (res[1]) casadi_copy(w22, 3, res[1]+69);
  /* #585: {NULL, @22, @33} = vertsplit(@32) */
  wr22 = wr32+3;
  wr33 = wr32+6;
  /* #586: output[1][24] = @22 */
  if (res[1]) casadi_copy(wr22, 3, res[1]+72);
  /* #587: @34 = @33[1] */
  w34 = wr33[1];
  /* #588: @40 = (@12*@34) */
  w40  = (w12*w34);
  /* #589: @40 = (@4*@40) */
  w40  = (w04*w40);
  /* #590: @36 = @33[0] */
  w36 = wr33[0];
  /* #591: @37 = (@3*@36) */
  w37  = (w03*w36);
  /* #592: @38 = (@6*@37) */
  w38  = (w06*w37);
  /* #593: @40 = (@40-@38) */
  w40 -= w38;
  /* #594: @38 = (@9*@40) */
  w38  = (w09*w40);
  /* #595: @39 = @33[2] */
  w39 = wr33[2];
  /* #596: @41 = (@8*@39) */
  w41  = (w08*w39);
  /* #597: @42 = (@7*@41) */
  w42  = (w07*w41);
  /* #598: @38 = (@38-@42) */
  w38 -= w42;
  /* #599: @36 = (@4*@36) */
  w36  = (w04*w36);
  /* #600: @42 = (@8*@36) */
  w42  = (w08*w36);
  /* #601: @39 = (@9*@39) */
  w39  = (w09*w39);
  /* #602: @44 = (@3*@39) */
  w44  = (w03*w39);
  /* #603: @42 = (@42+@44) */
  w42 += w44;
  /* #604: @38 = (@38+@42) */
  w38 += w42;
  /* #605: @40 = (@8*@40) */
  w40  = (w08*w40);
  /* #606: @39 = (@7*@39) */
  w39  = (w07*w39);
  /* #607: @40 = (@40+@39) */
  w40 += w39;
  /* #608: @39 = (@9*@36) */
  w39  = (w09*w36);
  /* #609: @41 = (@3*@41) */
  w41  = (w03*w41);
  /* #610: @39 = (@39-@41) */
  w39 -= w41;
  /* #611: @40 = (@40-@39) */
  w40 -= w39;
  /* #612: @39 = (@6*@34) */
  w39  = (w06*w34);
  /* #613: @41 = (@4*@39) */
  w41  = (w04*w39);
  /* #614: @41 = (-@41) */
  w41 = (- w41 );
  /* #615: @42 = (@12*@37) */
  w42  = (w12*w37);
  /* #616: @41 = (@41-@42) */
  w41 -= w42;
  /* #617: @33 = vertcat(@38, @40, @41) */
  rr=w33;
  *rr++ = w38;
  *rr++ = w40;
  *rr++ = w41;
  /* #618: @33 = (@1*@33) */
  for (i=0, rr=w33, cs=w33; i<3; ++i) (*rr++)  = (w01*(*cs++));
  /* #619: @33 = (@13*@33) */
  for (i=0, rr=w33, cs=w33; i<3; ++i) (*rr++)  = (w13*(*cs++));
  /* #620: @33 = (-@33) */
  for (i=0, rr=w33, cs=w33; i<3; ++i) *rr++ = (- *cs++ );
  /* #621: output[1][25] = @33 */
  if (res[1]) casadi_copy(w33, 3, res[1]+75);
  /* #622: @38 = (@5*@36) */
  w38  = (w05*w36);
  /* #623: @34 = (@34/@35) */
  w34 /= w35;
  /* #624: @40 = (@3*@34) */
  w40  = (w03*w34);
  /* #625: @38 = (@38+@40) */
  w38 += w40;
  /* #626: @43 = @15; (@43[1] += @38) */
  casadi_copy(w15, 2, w43);
  for (rr=w43+1, cs=(&w38); rr!=w43+2; rr+=1) *rr += *cs++;
  /* #627: @33 = project(@43) */
  casadi_project(w43, casadi_s1, w33, casadi_s2, w);
  /* #628: @34 = (@4*@34) */
  w34  = (w04*w34);
  /* #629: @38 = (@5*@37) */
  w38  = (w05*w37);
  /* #630: @34 = (@34-@38) */
  w34 -= w38;
  /* #631: (@33[2] += @34) */
  for (rr=w33+2, cs=(&w34); rr!=w33+3; rr+=1) *rr += *cs++;
  /* #632: @17 = project(@33) */
  casadi_project(w33, casadi_s2, w17, casadi_s4, w);
  /* #633: @34 = (-@37) */
  w34 = (- w37 );
  /* #634: (@17[3] += @34) */
  for (rr=w17+3, cs=(&w34); rr!=w17+4; rr+=1) *rr += *cs++;
  /* #635: @18 = project(@17) */
  casadi_project(w17, casadi_s4, w18, casadi_s5, w);
  /* #636: @34 = (-@36) */
  w34 = (- w36 );
  /* #637: (@18[5] += @34) */
  for (rr=w18+5, cs=(&w34); rr!=w18+6; rr+=1) *rr += *cs++;
  /* #638: @20 = project(@18) */
  casadi_project(w18, casadi_s5, w20, casadi_s7, w);
  /* #639: @36 = (@36/@12) */
  w36 /= w12;
  /* #640: @34 = (@10*@39) */
  w34  = (w10*w39);
  /* #641: @36 = (@36+@34) */
  w36 += w34;
  /* #642: (@20[5] += @36) */
  for (rr=w20+5, cs=(&w36); rr!=w20+6; rr+=1) *rr += *cs++;
  /* #643: @32 = dense(@20) */
  casadi_densify(w20, casadi_s7, w32, 0);
  /* #644: @39 = (@11*@39) */
  w39  = (w11*w39);
  /* #645: @37 = (@37/@12) */
  w37 /= w12;
  /* #646: @39 = (@39-@37) */
  w39 -= w37;
  /* #647: (@32[8] += @39) */
  for (rr=w32+8, cs=(&w39); rr!=w32+9; rr+=1) *rr += *cs++;
  /* #648: @33 = mac(@32,@14,@0) */
  casadi_copy(w00, 3, w33);
  for (i=0, rr=w33; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w32+j, ct=w14+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #649: output[1][26] = @33 */
  if (res[1]) casadi_copy(w33, 3, res[1]+78);
  /* #650: @45 = zeros(4x9,12nz) */
  casadi_clear(w45, 12);
  /* #651: @46 = zeros(3x1,0nz) */
  /* #652: @43 = ones(4x1,2nz) */
  casadi_fill(w43, 2, 1.);
  /* #653: {@39, @37} = vertsplit(@43) */
  w39 = w43[0];
  w37 = w43[1];
  /* #654: @2 = (@2*@39) */
  for (i=0, rr=w02; i<3; ++i) (*rr++) *= w39;
  /* #655: @2 = (@13*@2) */
  for (i=0, rr=w02, cs=w02; i<3; ++i) (*rr++)  = (w13*(*cs++));
  /* #656: @2 = (-@2) */
  for (i=0, rr=w02, cs=w02; i<3; ++i) *rr++ = (- *cs++ );
  /* #657: @33 = mac(@21,@37,@0) */
  casadi_copy(w00, 3, w33);
  casadi_mtimes(w21, casadi_s10, (&w37), casadi_s9, w33, casadi_s8, w, 0);
  /* #658: @18 = vertcat(@46, @2, @33) */
  rr=w18;
  for (i=0, cs=w02; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w33; i<3; ++i) *rr++ = *cs++;
  /* #659: @47 = @18[:6] */
  for (rr=w47, cs=w18+0; cs!=w18+6; cs+=1) *rr++ = *cs;
  /* #660: (@45[0, 1, 2, 3, 6, 9] = @47) */
  for (cii=casadi_s11, rr=w45, cs=w47; cii!=casadi_s11+6; ++cii, ++cs) rr[*cii] = *cs;
  /* #661: @37 = ones(4x1,1nz) */
  w37 = 1.;
  /* #662: {NULL, @39} = vertsplit(@37) */
  w39 = w37;
  /* #663: @2 = mac(@21,@39,@0) */
  casadi_copy(w00, 3, w02);
  casadi_mtimes(w21, casadi_s10, (&w39), casadi_s12, w02, casadi_s8, w, 0);
  /* #664: (@45[4:13:3] = @2) */
  for (rr=w45+4, cs=w02; rr!=w45+13; rr+=3) *rr = *cs++;
  /* #665: @39 = ones(4x1,1nz) */
  w39 = 1.;
  /* #666: {NULL, @37} = vertsplit(@39) */
  w37 = w39;
  /* #667: @2 = mac(@21,@37,@0) */
  casadi_copy(w00, 3, w02);
  casadi_mtimes(w21, casadi_s10, (&w37), casadi_s13, w02, casadi_s8, w, 0);
  /* #668: (@45[5:14:3] = @2) */
  for (rr=w45+5, cs=w02; rr!=w45+14; rr+=3) *rr = *cs++;
  /* #669: @48 = @45' */
  casadi_trans(w45,casadi_s15, w48, casadi_s14, iw);
  /* #670: @49 = dense(@48) */
  casadi_densify(w48, casadi_s14, w49, 0);
  /* #671: @50 = input[2][0] */
  wr50 = arg[2] ? arg[2] : casadi_zeros;
  /* #672: {@21, @32, @31, @30} = horzsplit(@50) */
  wr21 = wr50;
  wr32 = wr50+9;
  wr31 = wr50+18;
  wr30 = wr50+27;
  /* #673: {NULL, @2, @33} = vertsplit(@21) */
  wr02 = wr21+3;
  wr33 = wr21+6;
  /* #674: @37 = @33[1] */
  w37 = wr33[1];
  /* #675: @39 = (@12*@37) */
  w39  = (w12*w37);
  /* #676: @39 = (@4*@39) */
  w39  = (w04*w39);
  /* #677: @36 = @33[0] */
  w36 = wr33[0];
  /* #678: @34 = (@3*@36) */
  w34  = (w03*w36);
  /* #679: @38 = (@6*@34) */
  w38  = (w06*w34);
  /* #680: @39 = (@39-@38) */
  w39 -= w38;
  /* #681: @38 = (@9*@39) */
  w38  = (w09*w39);
  /* #682: @40 = @33[2] */
  w40 = wr33[2];
  /* #683: @41 = (@8*@40) */
  w41  = (w08*w40);
  /* #684: @42 = (@7*@41) */
  w42  = (w07*w41);
  /* #685: @38 = (@38-@42) */
  w38 -= w42;
  /* #686: @36 = (@4*@36) */
  w36  = (w04*w36);
  /* #687: @42 = (@8*@36) */
  w42  = (w08*w36);
  /* #688: @40 = (@9*@40) */
  w40  = (w09*w40);
  /* #689: @44 = (@3*@40) */
  w44  = (w03*w40);
  /* #690: @42 = (@42+@44) */
  w42 += w44;
  /* #691: @38 = (@38+@42) */
  w38 += w42;
  /* #692: @39 = (@8*@39) */
  w39  = (w08*w39);
  /* #693: @40 = (@7*@40) */
  w40  = (w07*w40);
  /* #694: @39 = (@39+@40) */
  w39 += w40;
  /* #695: @40 = (@9*@36) */
  w40  = (w09*w36);
  /* #696: @41 = (@3*@41) */
  w41  = (w03*w41);
  /* #697: @40 = (@40-@41) */
  w40 -= w41;
  /* #698: @39 = (@39-@40) */
  w39 -= w40;
  /* #699: @40 = (@6*@37) */
  w40  = (w06*w37);
  /* #700: @41 = (@4*@40) */
  w41  = (w04*w40);
  /* #701: @41 = (-@41) */
  w41 = (- w41 );
  /* #702: @42 = (@12*@34) */
  w42  = (w12*w34);
  /* #703: @41 = (@41-@42) */
  w41 -= w42;
  /* #704: @33 = vertcat(@38, @39, @41) */
  rr=w33;
  *rr++ = w38;
  *rr++ = w39;
  *rr++ = w41;
  /* #705: @33 = (@1*@33) */
  for (i=0, rr=w33, cs=w33; i<3; ++i) (*rr++)  = (w01*(*cs++));
  /* #706: @33 = (@13*@33) */
  for (i=0, rr=w33, cs=w33; i<3; ++i) (*rr++)  = (w13*(*cs++));
  /* #707: @33 = (-@33) */
  for (i=0, rr=w33, cs=w33; i<3; ++i) *rr++ = (- *cs++ );
  /* #708: @38 = (@5*@36) */
  w38  = (w05*w36);
  /* #709: @37 = (@37/@35) */
  w37 /= w35;
  /* #710: @39 = (@3*@37) */
  w39  = (w03*w37);
  /* #711: @38 = (@38+@39) */
  w38 += w39;
  /* #712: @43 = @15; (@43[1] += @38) */
  casadi_copy(w15, 2, w43);
  for (rr=w43+1, cs=(&w38); rr!=w43+2; rr+=1) *rr += *cs++;
  /* #713: @22 = project(@43) */
  casadi_project(w43, casadi_s1, w22, casadi_s2, w);
  /* #714: @37 = (@4*@37) */
  w37  = (w04*w37);
  /* #715: @38 = (@5*@34) */
  w38  = (w05*w34);
  /* #716: @37 = (@37-@38) */
  w37 -= w38;
  /* #717: (@22[2] += @37) */
  for (rr=w22+2, cs=(&w37); rr!=w22+3; rr+=1) *rr += *cs++;
  /* #718: @17 = project(@22) */
  casadi_project(w22, casadi_s2, w17, casadi_s4, w);
  /* #719: @37 = (-@34) */
  w37 = (- w34 );
  /* #720: (@17[3] += @37) */
  for (rr=w17+3, cs=(&w37); rr!=w17+4; rr+=1) *rr += *cs++;
  /* #721: @47 = project(@17) */
  casadi_project(w17, casadi_s4, w47, casadi_s5, w);
  /* #722: @37 = (-@36) */
  w37 = (- w36 );
  /* #723: (@47[5] += @37) */
  for (rr=w47+5, cs=(&w37); rr!=w47+6; rr+=1) *rr += *cs++;
  /* #724: @20 = project(@47) */
  casadi_project(w47, casadi_s5, w20, casadi_s7, w);
  /* #725: @36 = (@36/@12) */
  w36 /= w12;
  /* #726: @37 = (@10*@40) */
  w37  = (w10*w40);
  /* #727: @36 = (@36+@37) */
  w36 += w37;
  /* #728: (@20[5] += @36) */
  for (rr=w20+5, cs=(&w36); rr!=w20+6; rr+=1) *rr += *cs++;
  /* #729: @21 = dense(@20) */
  casadi_densify(w20, casadi_s7, w21, 0);
  /* #730: @40 = (@11*@40) */
  w40  = (w11*w40);
  /* #731: @34 = (@34/@12) */
  w34 /= w12;
  /* #732: @40 = (@40-@34) */
  w40 -= w34;
  /* #733: (@21[8] += @40) */
  for (rr=w21+8, cs=(&w40); rr!=w21+9; rr+=1) *rr += *cs++;
  /* #734: @22 = mac(@21,@14,@0) */
  casadi_copy(w00, 3, w22);
  for (i=0, rr=w22; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w21+j, ct=w14+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #735: @21 = vertcat(@2, @33, @22) */
  rr=w21;
  for (i=0, cs=wr02; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w33; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<3; ++i) *rr++ = *cs++;
  /* #736: {NULL, @2, @33} = vertsplit(@32) */
  wr02 = wr32+3;
  wr33 = wr32+6;
  /* #737: @40 = @33[1] */
  w40 = wr33[1];
  /* #738: @34 = (@12*@40) */
  w34  = (w12*w40);
  /* #739: @34 = (@4*@34) */
  w34  = (w04*w34);
  /* #740: @36 = @33[0] */
  w36 = wr33[0];
  /* #741: @37 = (@3*@36) */
  w37  = (w03*w36);
  /* #742: @38 = (@6*@37) */
  w38  = (w06*w37);
  /* #743: @34 = (@34-@38) */
  w34 -= w38;
  /* #744: @38 = (@9*@34) */
  w38  = (w09*w34);
  /* #745: @39 = @33[2] */
  w39 = wr33[2];
  /* #746: @41 = (@8*@39) */
  w41  = (w08*w39);
  /* #747: @42 = (@7*@41) */
  w42  = (w07*w41);
  /* #748: @38 = (@38-@42) */
  w38 -= w42;
  /* #749: @36 = (@4*@36) */
  w36  = (w04*w36);
  /* #750: @42 = (@8*@36) */
  w42  = (w08*w36);
  /* #751: @39 = (@9*@39) */
  w39  = (w09*w39);
  /* #752: @44 = (@3*@39) */
  w44  = (w03*w39);
  /* #753: @42 = (@42+@44) */
  w42 += w44;
  /* #754: @38 = (@38+@42) */
  w38 += w42;
  /* #755: @34 = (@8*@34) */
  w34  = (w08*w34);
  /* #756: @39 = (@7*@39) */
  w39  = (w07*w39);
  /* #757: @34 = (@34+@39) */
  w34 += w39;
  /* #758: @39 = (@9*@36) */
  w39  = (w09*w36);
  /* #759: @41 = (@3*@41) */
  w41  = (w03*w41);
  /* #760: @39 = (@39-@41) */
  w39 -= w41;
  /* #761: @34 = (@34-@39) */
  w34 -= w39;
  /* #762: @39 = (@6*@40) */
  w39  = (w06*w40);
  /* #763: @41 = (@4*@39) */
  w41  = (w04*w39);
  /* #764: @41 = (-@41) */
  w41 = (- w41 );
  /* #765: @42 = (@12*@37) */
  w42  = (w12*w37);
  /* #766: @41 = (@41-@42) */
  w41 -= w42;
  /* #767: @33 = vertcat(@38, @34, @41) */
  rr=w33;
  *rr++ = w38;
  *rr++ = w34;
  *rr++ = w41;
  /* #768: @33 = (@1*@33) */
  for (i=0, rr=w33, cs=w33; i<3; ++i) (*rr++)  = (w01*(*cs++));
  /* #769: @33 = (@13*@33) */
  for (i=0, rr=w33, cs=w33; i<3; ++i) (*rr++)  = (w13*(*cs++));
  /* #770: @33 = (-@33) */
  for (i=0, rr=w33, cs=w33; i<3; ++i) *rr++ = (- *cs++ );
  /* #771: @38 = (@5*@36) */
  w38  = (w05*w36);
  /* #772: @40 = (@40/@35) */
  w40 /= w35;
  /* #773: @34 = (@3*@40) */
  w34  = (w03*w40);
  /* #774: @38 = (@38+@34) */
  w38 += w34;
  /* #775: @43 = @15; (@43[1] += @38) */
  casadi_copy(w15, 2, w43);
  for (rr=w43+1, cs=(&w38); rr!=w43+2; rr+=1) *rr += *cs++;
  /* #776: @22 = project(@43) */
  casadi_project(w43, casadi_s1, w22, casadi_s2, w);
  /* #777: @40 = (@4*@40) */
  w40  = (w04*w40);
  /* #778: @38 = (@5*@37) */
  w38  = (w05*w37);
  /* #779: @40 = (@40-@38) */
  w40 -= w38;
  /* #780: (@22[2] += @40) */
  for (rr=w22+2, cs=(&w40); rr!=w22+3; rr+=1) *rr += *cs++;
  /* #781: @17 = project(@22) */
  casadi_project(w22, casadi_s2, w17, casadi_s4, w);
  /* #782: @40 = (-@37) */
  w40 = (- w37 );
  /* #783: (@17[3] += @40) */
  for (rr=w17+3, cs=(&w40); rr!=w17+4; rr+=1) *rr += *cs++;
  /* #784: @47 = project(@17) */
  casadi_project(w17, casadi_s4, w47, casadi_s5, w);
  /* #785: @40 = (-@36) */
  w40 = (- w36 );
  /* #786: (@47[5] += @40) */
  for (rr=w47+5, cs=(&w40); rr!=w47+6; rr+=1) *rr += *cs++;
  /* #787: @20 = project(@47) */
  casadi_project(w47, casadi_s5, w20, casadi_s7, w);
  /* #788: @36 = (@36/@12) */
  w36 /= w12;
  /* #789: @40 = (@10*@39) */
  w40  = (w10*w39);
  /* #790: @36 = (@36+@40) */
  w36 += w40;
  /* #791: (@20[5] += @36) */
  for (rr=w20+5, cs=(&w36); rr!=w20+6; rr+=1) *rr += *cs++;
  /* #792: @32 = dense(@20) */
  casadi_densify(w20, casadi_s7, w32, 0);
  /* #793: @39 = (@11*@39) */
  w39  = (w11*w39);
  /* #794: @37 = (@37/@12) */
  w37 /= w12;
  /* #795: @39 = (@39-@37) */
  w39 -= w37;
  /* #796: (@32[8] += @39) */
  for (rr=w32+8, cs=(&w39); rr!=w32+9; rr+=1) *rr += *cs++;
  /* #797: @22 = mac(@32,@14,@0) */
  casadi_copy(w00, 3, w22);
  for (i=0, rr=w22; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w32+j, ct=w14+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #798: @32 = vertcat(@2, @33, @22) */
  rr=w32;
  for (i=0, cs=wr02; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w33; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<3; ++i) *rr++ = *cs++;
  /* #799: {NULL, @2, @33} = vertsplit(@31) */
  wr02 = wr31+3;
  wr33 = wr31+6;
  /* #800: @39 = @33[1] */
  w39 = wr33[1];
  /* #801: @37 = (@12*@39) */
  w37  = (w12*w39);
  /* #802: @37 = (@4*@37) */
  w37  = (w04*w37);
  /* #803: @36 = @33[0] */
  w36 = wr33[0];
  /* #804: @40 = (@3*@36) */
  w40  = (w03*w36);
  /* #805: @38 = (@6*@40) */
  w38  = (w06*w40);
  /* #806: @37 = (@37-@38) */
  w37 -= w38;
  /* #807: @38 = (@9*@37) */
  w38  = (w09*w37);
  /* #808: @34 = @33[2] */
  w34 = wr33[2];
  /* #809: @41 = (@8*@34) */
  w41  = (w08*w34);
  /* #810: @42 = (@7*@41) */
  w42  = (w07*w41);
  /* #811: @38 = (@38-@42) */
  w38 -= w42;
  /* #812: @36 = (@4*@36) */
  w36  = (w04*w36);
  /* #813: @42 = (@8*@36) */
  w42  = (w08*w36);
  /* #814: @34 = (@9*@34) */
  w34  = (w09*w34);
  /* #815: @44 = (@3*@34) */
  w44  = (w03*w34);
  /* #816: @42 = (@42+@44) */
  w42 += w44;
  /* #817: @38 = (@38+@42) */
  w38 += w42;
  /* #818: @37 = (@8*@37) */
  w37  = (w08*w37);
  /* #819: @34 = (@7*@34) */
  w34  = (w07*w34);
  /* #820: @37 = (@37+@34) */
  w37 += w34;
  /* #821: @34 = (@9*@36) */
  w34  = (w09*w36);
  /* #822: @41 = (@3*@41) */
  w41  = (w03*w41);
  /* #823: @34 = (@34-@41) */
  w34 -= w41;
  /* #824: @37 = (@37-@34) */
  w37 -= w34;
  /* #825: @34 = (@6*@39) */
  w34  = (w06*w39);
  /* #826: @41 = (@4*@34) */
  w41  = (w04*w34);
  /* #827: @41 = (-@41) */
  w41 = (- w41 );
  /* #828: @42 = (@12*@40) */
  w42  = (w12*w40);
  /* #829: @41 = (@41-@42) */
  w41 -= w42;
  /* #830: @33 = vertcat(@38, @37, @41) */
  rr=w33;
  *rr++ = w38;
  *rr++ = w37;
  *rr++ = w41;
  /* #831: @33 = (@1*@33) */
  for (i=0, rr=w33, cs=w33; i<3; ++i) (*rr++)  = (w01*(*cs++));
  /* #832: @33 = (@13*@33) */
  for (i=0, rr=w33, cs=w33; i<3; ++i) (*rr++)  = (w13*(*cs++));
  /* #833: @33 = (-@33) */
  for (i=0, rr=w33, cs=w33; i<3; ++i) *rr++ = (- *cs++ );
  /* #834: @38 = (@5*@36) */
  w38  = (w05*w36);
  /* #835: @39 = (@39/@35) */
  w39 /= w35;
  /* #836: @37 = (@3*@39) */
  w37  = (w03*w39);
  /* #837: @38 = (@38+@37) */
  w38 += w37;
  /* #838: @43 = @15; (@43[1] += @38) */
  casadi_copy(w15, 2, w43);
  for (rr=w43+1, cs=(&w38); rr!=w43+2; rr+=1) *rr += *cs++;
  /* #839: @22 = project(@43) */
  casadi_project(w43, casadi_s1, w22, casadi_s2, w);
  /* #840: @39 = (@4*@39) */
  w39  = (w04*w39);
  /* #841: @38 = (@5*@40) */
  w38  = (w05*w40);
  /* #842: @39 = (@39-@38) */
  w39 -= w38;
  /* #843: (@22[2] += @39) */
  for (rr=w22+2, cs=(&w39); rr!=w22+3; rr+=1) *rr += *cs++;
  /* #844: @17 = project(@22) */
  casadi_project(w22, casadi_s2, w17, casadi_s4, w);
  /* #845: @39 = (-@40) */
  w39 = (- w40 );
  /* #846: (@17[3] += @39) */
  for (rr=w17+3, cs=(&w39); rr!=w17+4; rr+=1) *rr += *cs++;
  /* #847: @47 = project(@17) */
  casadi_project(w17, casadi_s4, w47, casadi_s5, w);
  /* #848: @39 = (-@36) */
  w39 = (- w36 );
  /* #849: (@47[5] += @39) */
  for (rr=w47+5, cs=(&w39); rr!=w47+6; rr+=1) *rr += *cs++;
  /* #850: @20 = project(@47) */
  casadi_project(w47, casadi_s5, w20, casadi_s7, w);
  /* #851: @36 = (@36/@12) */
  w36 /= w12;
  /* #852: @39 = (@10*@34) */
  w39  = (w10*w34);
  /* #853: @36 = (@36+@39) */
  w36 += w39;
  /* #854: (@20[5] += @36) */
  for (rr=w20+5, cs=(&w36); rr!=w20+6; rr+=1) *rr += *cs++;
  /* #855: @31 = dense(@20) */
  casadi_densify(w20, casadi_s7, w31, 0);
  /* #856: @34 = (@11*@34) */
  w34  = (w11*w34);
  /* #857: @40 = (@40/@12) */
  w40 /= w12;
  /* #858: @34 = (@34-@40) */
  w34 -= w40;
  /* #859: (@31[8] += @34) */
  for (rr=w31+8, cs=(&w34); rr!=w31+9; rr+=1) *rr += *cs++;
  /* #860: @22 = mac(@31,@14,@0) */
  casadi_copy(w00, 3, w22);
  for (i=0, rr=w22; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w31+j, ct=w14+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #861: @31 = vertcat(@2, @33, @22) */
  rr=w31;
  for (i=0, cs=wr02; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w33; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<3; ++i) *rr++ = *cs++;
  /* #862: {NULL, @2, @33} = vertsplit(@30) */
  wr02 = wr30+3;
  wr33 = wr30+6;
  /* #863: @34 = @33[1] */
  w34 = wr33[1];
  /* #864: @40 = (@12*@34) */
  w40  = (w12*w34);
  /* #865: @40 = (@4*@40) */
  w40  = (w04*w40);
  /* #866: @36 = @33[0] */
  w36 = wr33[0];
  /* #867: @39 = (@3*@36) */
  w39  = (w03*w36);
  /* #868: @38 = (@6*@39) */
  w38  = (w06*w39);
  /* #869: @40 = (@40-@38) */
  w40 -= w38;
  /* #870: @38 = (@9*@40) */
  w38  = (w09*w40);
  /* #871: @37 = @33[2] */
  w37 = wr33[2];
  /* #872: @41 = (@8*@37) */
  w41  = (w08*w37);
  /* #873: @42 = (@7*@41) */
  w42  = (w07*w41);
  /* #874: @38 = (@38-@42) */
  w38 -= w42;
  /* #875: @36 = (@4*@36) */
  w36  = (w04*w36);
  /* #876: @42 = (@8*@36) */
  w42  = (w08*w36);
  /* #877: @37 = (@9*@37) */
  w37  = (w09*w37);
  /* #878: @44 = (@3*@37) */
  w44  = (w03*w37);
  /* #879: @42 = (@42+@44) */
  w42 += w44;
  /* #880: @38 = (@38+@42) */
  w38 += w42;
  /* #881: @8 = (@8*@40) */
  w08 *= w40;
  /* #882: @7 = (@7*@37) */
  w07 *= w37;
  /* #883: @8 = (@8+@7) */
  w08 += w07;
  /* #884: @9 = (@9*@36) */
  w09 *= w36;
  /* #885: @41 = (@3*@41) */
  w41  = (w03*w41);
  /* #886: @9 = (@9-@41) */
  w09 -= w41;
  /* #887: @8 = (@8-@9) */
  w08 -= w09;
  /* #888: @6 = (@6*@34) */
  w06 *= w34;
  /* #889: @9 = (@4*@6) */
  w09  = (w04*w06);
  /* #890: @9 = (-@9) */
  w09 = (- w09 );
  /* #891: @41 = (@12*@39) */
  w41  = (w12*w39);
  /* #892: @9 = (@9-@41) */
  w09 -= w41;
  /* #893: @33 = vertcat(@38, @8, @9) */
  rr=w33;
  *rr++ = w38;
  *rr++ = w08;
  *rr++ = w09;
  /* #894: @33 = (@1*@33) */
  for (i=0, rr=w33, cs=w33; i<3; ++i) (*rr++)  = (w01*(*cs++));
  /* #895: @33 = (@13*@33) */
  for (i=0, rr=w33, cs=w33; i<3; ++i) (*rr++)  = (w13*(*cs++));
  /* #896: @33 = (-@33) */
  for (i=0, rr=w33, cs=w33; i<3; ++i) *rr++ = (- *cs++ );
  /* #897: @13 = (@5*@36) */
  w13  = (w05*w36);
  /* #898: @34 = (@34/@35) */
  w34 /= w35;
  /* #899: @3 = (@3*@34) */
  w03 *= w34;
  /* #900: @13 = (@13+@3) */
  w13 += w03;
  /* #901: (@15[1] += @13) */
  for (rr=w15+1, cs=(&w13); rr!=w15+2; rr+=1) *rr += *cs++;
  /* #902: @22 = project(@15) */
  casadi_project(w15, casadi_s1, w22, casadi_s2, w);
  /* #903: @4 = (@4*@34) */
  w04 *= w34;
  /* #904: @5 = (@5*@39) */
  w05 *= w39;
  /* #905: @4 = (@4-@5) */
  w04 -= w05;
  /* #906: (@22[2] += @4) */
  for (rr=w22+2, cs=(&w04); rr!=w22+3; rr+=1) *rr += *cs++;
  /* #907: @17 = project(@22) */
  casadi_project(w22, casadi_s2, w17, casadi_s4, w);
  /* #908: @4 = (-@39) */
  w04 = (- w39 );
  /* #909: (@17[3] += @4) */
  for (rr=w17+3, cs=(&w04); rr!=w17+4; rr+=1) *rr += *cs++;
  /* #910: @47 = project(@17) */
  casadi_project(w17, casadi_s4, w47, casadi_s5, w);
  /* #911: @4 = (-@36) */
  w04 = (- w36 );
  /* #912: (@47[5] += @4) */
  for (rr=w47+5, cs=(&w04); rr!=w47+6; rr+=1) *rr += *cs++;
  /* #913: @20 = project(@47) */
  casadi_project(w47, casadi_s5, w20, casadi_s7, w);
  /* #914: @36 = (@36/@12) */
  w36 /= w12;
  /* #915: @10 = (@10*@6) */
  w10 *= w06;
  /* #916: @36 = (@36+@10) */
  w36 += w10;
  /* #917: (@20[5] += @36) */
  for (rr=w20+5, cs=(&w36); rr!=w20+6; rr+=1) *rr += *cs++;
  /* #918: @30 = dense(@20) */
  casadi_densify(w20, casadi_s7, w30, 0);
  /* #919: @11 = (@11*@6) */
  w11 *= w06;
  /* #920: @39 = (@39/@12) */
  w39 /= w12;
  /* #921: @11 = (@11-@39) */
  w11 -= w39;
  /* #922: (@30[8] += @11) */
  for (rr=w30+8, cs=(&w11); rr!=w30+9; rr+=1) *rr += *cs++;
  /* #923: @0 = mac(@30,@14,@0) */
  for (i=0, rr=w00; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w30+j, ct=w14+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #924: @30 = vertcat(@2, @33, @0) */
  rr=w30;
  for (i=0, cs=wr02; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w33; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w00; i<3; ++i) *rr++ = *cs++;
  /* #925: @50 = horzcat(@21, @32, @31, @30) */
  rr=w50;
  for (i=0, cs=w21; i<9; ++i) *rr++ = *cs++;
  for (i=0, cs=w32; i<9; ++i) *rr++ = *cs++;
  for (i=0, cs=w31; i<9; ++i) *rr++ = *cs++;
  for (i=0, cs=w30; i<9; ++i) *rr++ = *cs++;
  /* #926: @49 = (@49+@50) */
  for (i=0, rr=w49, cs=w50; i<36; ++i) (*rr++) += (*cs++);
  /* #927: output[2][0] = @49 */
  casadi_copy(w49, 36, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int holybro_euler_err_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int holybro_euler_err_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int holybro_euler_err_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void holybro_euler_err_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int holybro_euler_err_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void holybro_euler_err_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void holybro_euler_err_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void holybro_euler_err_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int holybro_euler_err_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int holybro_euler_err_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real holybro_euler_err_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* holybro_euler_err_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* holybro_euler_err_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* holybro_euler_err_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s16;
    case 1: return casadi_s17;
    case 2: return casadi_s18;
    case 3: return casadi_s19;
    case 4: return casadi_s20;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* holybro_euler_err_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s16;
    case 1: return casadi_s17;
    case 2: return casadi_s18;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int holybro_euler_err_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9;
  if (sz_res) *sz_res = 12;
  if (sz_iw) *sz_iw = 5;
  if (sz_w) *sz_w = 347;
  return 0;
}

CASADI_SYMBOL_EXPORT int holybro_euler_err_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 12*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 5*sizeof(casadi_int);
  if (sz_w) *sz_w = 347*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
