/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) holybro_euler_err_cost_y_e_fun_jac_ut_xt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

static const casadi_int casadi_s0[3] = {9, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {13, 1, 1};
static const casadi_int casadi_s4[21] = 
  {9, 9, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 0, 1, 2, 3,
  4, 5, 6, 7, 8};
static const casadi_int casadi_s5[3] = {9, 0, 1};

/* holybro_euler_err_cost_y_e_fun_jac_ut_xt:(i0[9],i1[0],i2[0],i3[],i4[13])->(o0[9],o1[9x9,9nz],o2[9x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *w00=w+0, *w01=w+3, w02, w03, w04, *w05=w+9, *w06=w+18, *w07=w+27, w08, w09, w10;
  const casadi_real *cs;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 3, w00);
  /* #1: @1 = input[4][0] */
  casadi_copy(arg[4], 3, w01);
  /* #2: @0 = (@0-@1) */
  for (i=0, rr=w00, cs=w01; i<3; ++i) (*rr++) -= (*cs++);
  /* #3: output[0][0] = @0 */
  casadi_copy(w00, 3, res[0]);
  /* #4: @0 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 3, w00);
  /* #5: @1 = input[4][1] */
  casadi_copy(arg[4] ? arg[4]+3 : 0, 3, w01);
  /* #6: @0 = (@0-@1) */
  for (i=0, rr=w00, cs=w01; i<3; ++i) (*rr++) -= (*cs++);
  /* #7: output[0][1] = @0 */
  if (res[0]) casadi_copy(w00, 3, res[0]+3);
  /* #8: @0 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+6 : 0, 3, w00);
  /* #9: @2 = @0[0] */
  for (rr=(&w02), cs=w00+0; cs!=w00+1; cs+=1) *rr++ = *cs;
  /* #10: @1 = input[4][2] */
  casadi_copy(arg[4] ? arg[4]+6 : 0, 3, w01);
  /* #11: @3 = @1[0] */
  for (rr=(&w03), cs=w01+0; cs!=w01+1; cs+=1) *rr++ = *cs;
  /* #12: @2 = (@2-@3) */
  w02 -= w03;
  /* #13: output[0][2] = @2 */
  if (res[0]) res[0][6] = w02;
  /* #14: @2 = @0[1] */
  for (rr=(&w02), cs=w00+1; cs!=w00+2; cs+=1) *rr++ = *cs;
  /* #15: @3 = @1[1] */
  for (rr=(&w03), cs=w01+1; cs!=w01+2; cs+=1) *rr++ = *cs;
  /* #16: @2 = (@2-@3) */
  w02 -= w03;
  /* #17: output[0][3] = @2 */
  if (res[0]) res[0][7] = w02;
  /* #18: @2 = @0[2] */
  for (rr=(&w02), cs=w00+2; cs!=w00+3; cs+=1) *rr++ = *cs;
  /* #19: @3 = @1[2] */
  for (rr=(&w03), cs=w01+2; cs!=w01+3; cs+=1) *rr++ = *cs;
  /* #20: @2 = (@2-@3) */
  w02 -= w03;
  /* #21: @3 = sin(@2) */
  w03 = sin( w02 );
  /* #22: @2 = cos(@2) */
  w02 = cos( w02 );
  /* #23: @4 = atan2(@3,@2) */
  w04  = atan2(w03,w02);
  /* #24: output[0][4] = @4 */
  if (res[0]) res[0][8] = w04;
  /* #25: @5 = zeros(9x9,9nz) */
  casadi_clear(w05, 9);
  /* #26: @6 = ones(9x1) */
  casadi_fill(w06, 9, 1.);
  /* #27: {@1, @0, @7} = vertsplit(@6) */
  casadi_copy(w06, 3, w01);
  casadi_copy(w06+3, 3, w00);
  casadi_copy(w06+6, 3, w07);
  /* #28: @4 = @7[0] */
  for (rr=(&w04), cs=w07+0; cs!=w07+1; cs+=1) *rr++ = *cs;
  /* #29: @8 = @7[1] */
  for (rr=(&w08), cs=w07+1; cs!=w07+2; cs+=1) *rr++ = *cs;
  /* #30: @9 = @7[2] */
  for (rr=(&w09), cs=w07+2; cs!=w07+3; cs+=1) *rr++ = *cs;
  /* #31: @10 = (@2*@9) */
  w10  = (w02*w09);
  /* #32: @2 = (@2*@10) */
  w02 *= w10;
  /* #33: @9 = (@3*@9) */
  w09  = (w03*w09);
  /* #34: @3 = (@3*@9) */
  w03 *= w09;
  /* #35: @2 = (@2+@3) */
  w02 += w03;
  /* #36: @6 = vertcat(@1, @0, @4, @8, @2) */
  rr=w06;
  for (i=0, cs=w01; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w00; i<3; ++i) *rr++ = *cs++;
  *rr++ = w04;
  *rr++ = w08;
  *rr++ = w02;
  /* #37: (@5[:9] = @6) */
  for (rr=w05+0, cs=w06; rr!=w05+9; rr+=1) *rr = *cs++;
  /* #38: output[1][0] = @5 */
  casadi_copy(w05, 9, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int holybro_euler_err_cost_y_e_fun_jac_ut_xt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int holybro_euler_err_cost_y_e_fun_jac_ut_xt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int holybro_euler_err_cost_y_e_fun_jac_ut_xt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void holybro_euler_err_cost_y_e_fun_jac_ut_xt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int holybro_euler_err_cost_y_e_fun_jac_ut_xt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void holybro_euler_err_cost_y_e_fun_jac_ut_xt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void holybro_euler_err_cost_y_e_fun_jac_ut_xt_incref(void) {
}

CASADI_SYMBOL_EXPORT void holybro_euler_err_cost_y_e_fun_jac_ut_xt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int holybro_euler_err_cost_y_e_fun_jac_ut_xt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int holybro_euler_err_cost_y_e_fun_jac_ut_xt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real holybro_euler_err_cost_y_e_fun_jac_ut_xt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* holybro_euler_err_cost_y_e_fun_jac_ut_xt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* holybro_euler_err_cost_y_e_fun_jac_ut_xt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* holybro_euler_err_cost_y_e_fun_jac_ut_xt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* holybro_euler_err_cost_y_e_fun_jac_ut_xt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int holybro_euler_err_cost_y_e_fun_jac_ut_xt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10;
  if (sz_res) *sz_res = 6;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 33;
  return 0;
}

CASADI_SYMBOL_EXPORT int holybro_euler_err_cost_y_e_fun_jac_ut_xt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 6*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 33*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
