/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) holybro_euler_err_cost_y_0_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {9, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[3] = {13, 1, 1};

/* holybro_euler_err_cost_y_0_fun:(i0[9],i1[4],i2[0],i3[],i4[13])->(o0[13]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *w0=w+0, *w1=w+3, w2, w3, *w4=w+8, *w5=w+12;
  const casadi_real *cs;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 3, w0);
  /* #1: @1 = input[4][0] */
  casadi_copy(arg[4], 3, w1);
  /* #2: @0 = (@0-@1) */
  for (i=0, rr=w0, cs=w1; i<3; ++i) (*rr++) -= (*cs++);
  /* #3: output[0][0] = @0 */
  casadi_copy(w0, 3, res[0]);
  /* #4: @0 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 3, w0);
  /* #5: @1 = input[4][1] */
  casadi_copy(arg[4] ? arg[4]+3 : 0, 3, w1);
  /* #6: @0 = (@0-@1) */
  for (i=0, rr=w0, cs=w1; i<3; ++i) (*rr++) -= (*cs++);
  /* #7: output[0][1] = @0 */
  if (res[0]) casadi_copy(w0, 3, res[0]+3);
  /* #8: @0 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+6 : 0, 3, w0);
  /* #9: @2 = @0[0] */
  for (rr=(&w2), cs=w0+0; cs!=w0+1; cs+=1) *rr++ = *cs;
  /* #10: @1 = input[4][2] */
  casadi_copy(arg[4] ? arg[4]+6 : 0, 3, w1);
  /* #11: @3 = @1[0] */
  for (rr=(&w3), cs=w1+0; cs!=w1+1; cs+=1) *rr++ = *cs;
  /* #12: @2 = (@2-@3) */
  w2 -= w3;
  /* #13: output[0][2] = @2 */
  if (res[0]) res[0][6] = w2;
  /* #14: @2 = @0[1] */
  for (rr=(&w2), cs=w0+1; cs!=w0+2; cs+=1) *rr++ = *cs;
  /* #15: @3 = @1[1] */
  for (rr=(&w3), cs=w1+1; cs!=w1+2; cs+=1) *rr++ = *cs;
  /* #16: @2 = (@2-@3) */
  w2 -= w3;
  /* #17: output[0][3] = @2 */
  if (res[0]) res[0][7] = w2;
  /* #18: @2 = @0[2] */
  for (rr=(&w2), cs=w0+2; cs!=w0+3; cs+=1) *rr++ = *cs;
  /* #19: @3 = @1[2] */
  for (rr=(&w3), cs=w1+2; cs!=w1+3; cs+=1) *rr++ = *cs;
  /* #20: @2 = (@2-@3) */
  w2 -= w3;
  /* #21: @3 = sin(@2) */
  w3 = sin( w2 );
  /* #22: @2 = cos(@2) */
  w2 = cos( w2 );
  /* #23: @3 = atan2(@3,@2) */
  w3  = atan2(w3,w2);
  /* #24: output[0][4] = @3 */
  if (res[0]) res[0][8] = w3;
  /* #25: @3 = input[1][0] */
  w3 = arg[1] ? arg[1][0] : 0;
  /* #26: @1 = input[1][1] */
  casadi_copy(arg[1] ? arg[1]+1 : 0, 3, w1);
  /* #27: @4 = vertcat(@3, @1) */
  rr=w4;
  *rr++ = w3;
  for (i=0, cs=w1; i<3; ++i) *rr++ = *cs++;
  /* #28: @5 = input[4][3] */
  casadi_copy(arg[4] ? arg[4]+9 : 0, 4, w5);
  /* #29: @4 = (@4-@5) */
  for (i=0, rr=w4, cs=w5; i<4; ++i) (*rr++) -= (*cs++);
  /* #30: output[0][5] = @4 */
  if (res[0]) casadi_copy(w4, 4, res[0]+9);
  return 0;
}

CASADI_SYMBOL_EXPORT int holybro_euler_err_cost_y_0_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int holybro_euler_err_cost_y_0_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int holybro_euler_err_cost_y_0_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void holybro_euler_err_cost_y_0_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int holybro_euler_err_cost_y_0_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void holybro_euler_err_cost_y_0_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void holybro_euler_err_cost_y_0_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void holybro_euler_err_cost_y_0_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int holybro_euler_err_cost_y_0_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int holybro_euler_err_cost_y_0_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real holybro_euler_err_cost_y_0_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* holybro_euler_err_cost_y_0_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* holybro_euler_err_cost_y_0_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* holybro_euler_err_cost_y_0_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* holybro_euler_err_cost_y_0_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int holybro_euler_err_cost_y_0_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 16;
  return 0;
}

CASADI_SYMBOL_EXPORT int holybro_euler_err_cost_y_0_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 16*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
