/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) holybro_euler_err_cost_y_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_trans CASADI_PREFIX(trans)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[17] = 
  {13, 13, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 1,
  12};
static const casadi_int casadi_s1[3] = {9, 1, 1};
static const casadi_int casadi_s2[3] = {4, 1, 1};
static const casadi_int casadi_s3[3] = {0, 1, 1};
static const casadi_int casadi_s4[3] = {13, 1, 1};
static const casadi_int casadi_s5[3] = {0, 0, 1};

static const casadi_real casadi_zeros[13] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0.};

/* holybro_euler_err_cost_y_hess:(i0[9],i1[4],i2[0],i3[13],i4[],i5[13])->(o0[13x13,1nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, w0, *w1=w+1, *w2=w+4, w3, w4, *w5=w+9, w6, w7, w8, w9;
  const casadi_real *cs, *wr5;
  /* #0: @0 = zeros(13x13,1nz) */
  w0 = 0.;
  /* #1: @1 = zeros(3x1) */
  casadi_clear(w1, 3);
  /* #2: @2 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+6 : 0, 3, w2);
  /* #3: @3 = @2[2] */
  for (rr=(&w3), cs=w2+2; cs!=w2+3; cs+=1) *rr++ = *cs;
  /* #4: @2 = input[5][2] */
  casadi_copy(arg[5] ? arg[5]+6 : 0, 3, w2);
  /* #5: @4 = @2[2] */
  for (rr=(&w4), cs=w2+2; cs!=w2+3; cs+=1) *rr++ = *cs;
  /* #6: @3 = (@3-@4) */
  w3 -= w4;
  /* #7: @4 = sin(@3) */
  w4 = sin( w3 );
  /* #8: @5 = input[3][0] */
  wr5 = arg[3] ? arg[3] : casadi_zeros;
  /* #9: {NULL, NULL, NULL, NULL, @6, NULL} = vertsplit(@5) */
  w6 = wr5[8];
  /* #10: @7 = (@4*@6) */
  w7  = (w4*w6);
  /* #11: @3 = cos(@3) */
  w3 = cos( w3 );
  /* #12: @5 = ones(13x1) */
  casadi_fill(w5, 13, 1.);
  /* #13: {NULL, NULL, NULL, NULL, @2} = vertsplit(@5) */
  casadi_copy(w5+10, 3, w2);
  /* #14: @8 = @2[2] */
  for (rr=(&w8), cs=w2+2; cs!=w2+3; cs+=1) *rr++ = *cs;
  /* #15: @9 = (@3*@8) */
  w9  = (w3*w8);
  /* #16: @7 = (@7*@9) */
  w7 *= w9;
  /* #17: @9 = (@6*@9) */
  w9  = (w6*w9);
  /* #18: @9 = (@4*@9) */
  w9  = (w4*w9);
  /* #19: @7 = (@7+@9) */
  w7 += w9;
  /* #20: @4 = (@4*@8) */
  w4 *= w8;
  /* #21: @8 = (@6*@4) */
  w8  = (w6*w4);
  /* #22: @8 = (@3*@8) */
  w8  = (w3*w8);
  /* #23: @8 = (-@8) */
  w8 = (- w8 );
  /* #24: @3 = (@3*@6) */
  w3 *= w6;
  /* #25: @3 = (@3*@4) */
  w3 *= w4;
  /* #26: @8 = (@8-@3) */
  w8 -= w3;
  /* #27: @7 = (@7+@8) */
  w7 += w8;
  /* #28: (@1[2] += @7) */
  for (rr=w1+2, cs=(&w7); rr!=w1+3; rr+=1) *rr += *cs++;
  /* #29: @7 = @1[2] */
  for (rr=(&w7), cs=w1+2; cs!=w1+3; cs+=1) *rr++ = *cs;
  /* #30: (@0[0] = @7) */
  for (rr=(&w0)+0, cs=(&w7); rr!=(&w0)+1; rr+=1) *rr = *cs++;
  /* #31: @7 = @0' */
  casadi_trans((&w0),casadi_s0, (&w7), casadi_s0, iw);
  /* #32: output[0][0] = @7 */
  if (res[0]) res[0][0] = w7;
  return 0;
}

CASADI_SYMBOL_EXPORT int holybro_euler_err_cost_y_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int holybro_euler_err_cost_y_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int holybro_euler_err_cost_y_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void holybro_euler_err_cost_y_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int holybro_euler_err_cost_y_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void holybro_euler_err_cost_y_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void holybro_euler_err_cost_y_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void holybro_euler_err_cost_y_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int holybro_euler_err_cost_y_hess_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int holybro_euler_err_cost_y_hess_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real holybro_euler_err_cost_y_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* holybro_euler_err_cost_y_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* holybro_euler_err_cost_y_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* holybro_euler_err_cost_y_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    case 2: return casadi_s3;
    case 3: return casadi_s4;
    case 4: return casadi_s5;
    case 5: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* holybro_euler_err_cost_y_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int holybro_euler_err_cost_y_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 7;
  if (sz_iw) *sz_iw = 14;
  if (sz_w) *sz_w = 26;
  return 0;
}

CASADI_SYMBOL_EXPORT int holybro_euler_err_cost_y_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 7*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 14*sizeof(casadi_int);
  if (sz_w) *sz_w = 26*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
