/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) holybro_euler_err_cost_y_fun_jac_ut_xt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

static const casadi_int casadi_s0[3] = {9, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[3] = {13, 1, 1};
static const casadi_int casadi_s5[29] = 
  {13, 13, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11, 12, 13,
  4, 5, 6, 7, 8, 9, 10, 11,
  12, 0, 1, 2, 3};
static const casadi_int casadi_s6[3] = {13, 0, 1};

/* holybro_euler_err_cost_y_fun_jac_ut_xt:(i0[9],i1[4],i2[0],i3[],i4[13])->(o0[13],o1[13x13,13nz],o2[13x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *w00=w+0, *w01=w+3, w02, w03, w04, *w05=w+9, *w06=w+13, *w07=w+17, *w08=w+30, *w09=w+43, *w10=w+46;
  casadi_real w11, w12, w13, w14;
  const casadi_real *cs;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 3, w00);
  /* #1: @1 = input[4][0] */
  casadi_copy(arg[4], 3, w01);
  /* #2: @0 = (@0-@1) */
  for (i=0, rr=w00, cs=w01; i<3; ++i) (*rr++) -= (*cs++);
  /* #3: output[0][0] = @0 */
  casadi_copy(w00, 3, res[0]);
  /* #4: @0 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 3, w00);
  /* #5: @1 = input[4][1] */
  casadi_copy(arg[4] ? arg[4]+3 : 0, 3, w01);
  /* #6: @0 = (@0-@1) */
  for (i=0, rr=w00, cs=w01; i<3; ++i) (*rr++) -= (*cs++);
  /* #7: output[0][1] = @0 */
  if (res[0]) casadi_copy(w00, 3, res[0]+3);
  /* #8: @0 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+6 : 0, 3, w00);
  /* #9: @2 = @0[0] */
  for (rr=(&w02), cs=w00+0; cs!=w00+1; cs+=1) *rr++ = *cs;
  /* #10: @1 = input[4][2] */
  casadi_copy(arg[4] ? arg[4]+6 : 0, 3, w01);
  /* #11: @3 = @1[0] */
  for (rr=(&w03), cs=w01+0; cs!=w01+1; cs+=1) *rr++ = *cs;
  /* #12: @2 = (@2-@3) */
  w02 -= w03;
  /* #13: output[0][2] = @2 */
  if (res[0]) res[0][6] = w02;
  /* #14: @2 = @0[1] */
  for (rr=(&w02), cs=w00+1; cs!=w00+2; cs+=1) *rr++ = *cs;
  /* #15: @3 = @1[1] */
  for (rr=(&w03), cs=w01+1; cs!=w01+2; cs+=1) *rr++ = *cs;
  /* #16: @2 = (@2-@3) */
  w02 -= w03;
  /* #17: output[0][3] = @2 */
  if (res[0]) res[0][7] = w02;
  /* #18: @2 = @0[2] */
  for (rr=(&w02), cs=w00+2; cs!=w00+3; cs+=1) *rr++ = *cs;
  /* #19: @3 = @1[2] */
  for (rr=(&w03), cs=w01+2; cs!=w01+3; cs+=1) *rr++ = *cs;
  /* #20: @2 = (@2-@3) */
  w02 -= w03;
  /* #21: @3 = sin(@2) */
  w03 = sin( w02 );
  /* #22: @2 = cos(@2) */
  w02 = cos( w02 );
  /* #23: @4 = atan2(@3,@2) */
  w04  = atan2(w03,w02);
  /* #24: output[0][4] = @4 */
  if (res[0]) res[0][8] = w04;
  /* #25: @4 = input[1][0] */
  w04 = arg[1] ? arg[1][0] : 0;
  /* #26: @1 = input[1][1] */
  casadi_copy(arg[1] ? arg[1]+1 : 0, 3, w01);
  /* #27: @5 = vertcat(@4, @1) */
  rr=w05;
  *rr++ = w04;
  for (i=0, cs=w01; i<3; ++i) *rr++ = *cs++;
  /* #28: @6 = input[4][3] */
  casadi_copy(arg[4] ? arg[4]+9 : 0, 4, w06);
  /* #29: @5 = (@5-@6) */
  for (i=0, rr=w05, cs=w06; i<4; ++i) (*rr++) -= (*cs++);
  /* #30: output[0][5] = @5 */
  if (res[0]) casadi_copy(w05, 4, res[0]+9);
  /* #31: @7 = zeros(13x13,13nz) */
  casadi_clear(w07, 13);
  /* #32: @8 = ones(13x1) */
  casadi_fill(w08, 13, 1.);
  /* #33: {@4, @1, @0, @9, @10} = vertsplit(@8) */
  w04 = w08[0];
  casadi_copy(w08+1, 3, w01);
  casadi_copy(w08+4, 3, w00);
  casadi_copy(w08+7, 3, w09);
  casadi_copy(w08+10, 3, w10);
  /* #34: @11 = @10[0] */
  for (rr=(&w11), cs=w10+0; cs!=w10+1; cs+=1) *rr++ = *cs;
  /* #35: @12 = @10[1] */
  for (rr=(&w12), cs=w10+1; cs!=w10+2; cs+=1) *rr++ = *cs;
  /* #36: @13 = @10[2] */
  for (rr=(&w13), cs=w10+2; cs!=w10+3; cs+=1) *rr++ = *cs;
  /* #37: @14 = (@2*@13) */
  w14  = (w02*w13);
  /* #38: @2 = (@2*@14) */
  w02 *= w14;
  /* #39: @13 = (@3*@13) */
  w13  = (w03*w13);
  /* #40: @3 = (@3*@13) */
  w03 *= w13;
  /* #41: @2 = (@2+@3) */
  w02 += w03;
  /* #42: @8 = vertcat(@0, @9, @11, @12, @2, @4, @1) */
  rr=w08;
  for (i=0, cs=w00; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w09; i<3; ++i) *rr++ = *cs++;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w02;
  *rr++ = w04;
  for (i=0, cs=w01; i<3; ++i) *rr++ = *cs++;
  /* #43: (@7[:13] = @8) */
  for (rr=w07+0, cs=w08; rr!=w07+13; rr+=1) *rr = *cs++;
  /* #44: output[1][0] = @7 */
  casadi_copy(w07, 13, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int holybro_euler_err_cost_y_fun_jac_ut_xt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int holybro_euler_err_cost_y_fun_jac_ut_xt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int holybro_euler_err_cost_y_fun_jac_ut_xt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void holybro_euler_err_cost_y_fun_jac_ut_xt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int holybro_euler_err_cost_y_fun_jac_ut_xt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void holybro_euler_err_cost_y_fun_jac_ut_xt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void holybro_euler_err_cost_y_fun_jac_ut_xt_incref(void) {
}

CASADI_SYMBOL_EXPORT void holybro_euler_err_cost_y_fun_jac_ut_xt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int holybro_euler_err_cost_y_fun_jac_ut_xt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int holybro_euler_err_cost_y_fun_jac_ut_xt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real holybro_euler_err_cost_y_fun_jac_ut_xt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* holybro_euler_err_cost_y_fun_jac_ut_xt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* holybro_euler_err_cost_y_fun_jac_ut_xt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* holybro_euler_err_cost_y_fun_jac_ut_xt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* holybro_euler_err_cost_y_fun_jac_ut_xt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int holybro_euler_err_cost_y_fun_jac_ut_xt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 12;
  if (sz_res) *sz_res = 8;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 53;
  return 0;
}

CASADI_SYMBOL_EXPORT int holybro_euler_err_cost_y_fun_jac_ut_xt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 12*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 8*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 53*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
